// Code generated by hack/gen-profiles. DO NOT EDIT.
//
// Regenerate with:
//	go run ./hack/gen-profiles

package nuclei

import "github.com/flanksource/recon/internal/engines"

// communityProfiles are nuclei's own scan profiles, imported from the templates
// release. They are ordinary profiles here: previewable, editable, and validated
// against the same option catalog as everything else.
//
// They are snapshots. Re-run the generator after updating templates.
var communityProfiles = []engines.DefaultProfile{
	{
		Name: "ai",
		Comment: "Nuclei Configuration Profile for AI Security Testing\n" +
			"With the rapid adoption of AI and LLM technologies across industries, securing AI infrastructure\n" +
			"has become critical. Organizations are deploying AI models, vector databases, ML platforms, and\n" +
			"LLM applications at an unprecedented pace, often without proper security assessments.\n" +
			"This profile enables comprehensive security testing of AI ecosystems, covering: LLM Application Security, AI Infrastructure/services and AI Development Tools",
		Config: map[string]any{
			"tags": []any{"ai"},
		},
	},
	{
		Name: "alibaba-cloud-config",
		Comment: "Nuclei Configuration Profile for Scanning aliyun ACLs\n" +
			"This configuration file is specifically tailored for detecting issues in aliyun Access Control Lists (ACLs) using Nuclei.\n" +
			"This profile is focused on identifying misconfigurations and vulnerabilities in aliyun ACLs. Proper configuration of ACLs is crucial for securing aliyun resources and ensuring that only authorized entities have access.\n" +
			"Included Templates:\n" +
			"This configuration references specific templates tagged with 'alibaba-cloud-config' to cover comprehensive scanning of aliyun ACLs.\n" +
			"\n" +
			"Self-contained templates are enabled because every template this profile\n" +
			"selects declares one; without it the profile runs nothing.",
		Config: map[string]any{
			"code":                  true,
			"tags":                  []any{"alibaba-cloud-config"},
			"var":                   []any{"region=cn-hangzhou"},
			"enable-self-contained": true,
		},
	},
	{
		Name: "all",
		Comment: "Nuclei Configuration Profile for Comprehensive Detection\n" +
			"This configuration file is specifically tailored for performing comprehensive scans using Nuclei, All the avaliable templates are loaded using this profile.\n" +
			"This profile is focused on identifying a wide range of security issues across different types of protocols and services. It includes templates for HTTP, TCP, JavaScript, DNS, and SSL to ensure thorough coverage of potential vulnerabilities.",
		Config: map[string]any{
			"type": []any{"http", "tcp", "javascript", "dns", "ssl"},
		},
	},
	{
		Name: "aws-cloud-config",
		Comment: "Nuclei Configuration Profile for Scanning AWS ACLs\n" +
			"This configuration file is specifically tailored for detecting issues in AWS Access Control Lists (ACLs) using Nuclei.\n" +
			"This profile is focused on identifying misconfigurations and vulnerabilities in AWS ACLs. Proper configuration of ACLs is crucial for securing AWS resources and ensuring that only authorized entities have access.\n" +
			"Included Templates:\n" +
			"This configuration references specific templates tagged with 'aws-cloud-config' to cover comprehensive scanning of AWS ACLs.\n" +
			"\n" +
			"Self-contained templates are enabled because every template this profile\n" +
			"selects declares one; without it the profile runs nothing.",
		Config: map[string]any{
			"code":                  true,
			"tags":                  []any{"aws-cloud-config"},
			"var":                   []any{"region=us-east-1"},
			"enable-self-contained": true,
		},
	},
	{
		Name: "azure-cloud-config",
		Comment: "Nuclei Configuration Profile for Scanning Azure ACLs\n" +
			"This configuration file is specifically tailored for detecting issues in Azure Access Control Lists (ACLs) using Nuclei.\n" +
			"This profile is focused on identifying misconfigurations and vulnerabilities in Azure ACLs. Proper configuration of ACLs is crucial for securing Azure resources and ensuring that only authorized entities have access.\n" +
			"Included Templates:\n" +
			"This configuration references specific templates tagged with 'azure-cloud-config' to cover comprehensive scanning of Azure ACLs.\n" +
			"\n" +
			"Self-contained templates are enabled because every template this profile\n" +
			"selects declares one; without it the profile runs nothing.",
		Config: map[string]any{
			"code":                  true,
			"tags":                  []any{"azure-cloud-config"},
			"enable-self-contained": true,
		},
	},
	{
		Name: "cloud",
		Comment: "Nuclei Configuration Profile for Cloud Detection\n" +
			"This configuration file is specifically tailored for detecting cloud-related vulnerabilities and misconfigurations using Nuclei.\n" +
			"This profile is focused on identifying security issues in cloud environments. It includes templates that help detect vulnerabilities and misconfigurations in cloud services and infrastructure, ensuring the security of cloud deployments.",
		Config: map[string]any{
			"tags": []any{"cloud", "devops"},
		},
	},
	{
		Name: "compliance",
		Comment: "Nuclei Configuration Profile for Compliance Detection\n" +
			"This configuration file is specifically tailored for detecting compliance-related issues using Nuclei.\n" +
			"This profile is focused on identifying a wide range of security issues to ensure compliance with various security standards and best practices. It includes templates for detecting misconfigurations, vulnerabilities, exposures, and other security risks.",
		Config: map[string]any{
			"tags": []any{"misconfig", "cve", "exposure", "default-login", "xss", "lfi", "edb", "rce", "sqli", "unauth", "default-login", "ssrf", "redirect", "disclosure", "takeover", "traversal", "generic", "deserialization", "ssl", "keys", "token"},
		},
	},
	{
		Name: "cves",
		Comment: "Nuclei Configuration Profile for CVEs Detection\n" +
			"This configuration file is specifically tailored for detecting Common Vulnerabilities and Exposures (CVEs) using Nuclei.\n" +
			"This profile is focused on identifying vulnerabilities listed in the Common Vulnerabilities and Exposures (CVE) database. Detecting CVEs is essential for mitigating risks associated with known security flaws in software and systems.",
		Config: map[string]any{
			"templates": []any{"http/cves/", "http/cnvd/", "network/cves/", "javascript/cves/"},
		},
	},
	{
		Name: "default-login",
		Comment: "Nuclei Configuration Profile for Default Logins Detection\n" +
			"This configuration file is specifically tailored for detecting default login credentials using Nuclei.\n" +
			"This profile is focused on identifying instances where default login credentials are being used. Default logins can pose significant security risks as they are often targeted by attackers to gain unauthorized access to systems.",
		Config: map[string]any{
			"templates": []any{"http/default-logins/", "network/default-login/", "javascript/default-logins/"},
		},
	},
	{
		Name: "gcp-cloud-config",
		Comment: "Nuclei Configuration Profile for Scanning Azure ACLs\n" +
			"This configuration file is specifically tailored for detecting misconfigurations in GCP environment using Nuclei.\n" +
			"This profile is focused on identifying misconfigurations and vulnerabilities in GCP environment.\n" +
			"Included Templates:\n" +
			"This configuration references specific templates tagged with 'gcp-cloud-config' to cover comprehensive scanning of Azure ACLs.\n" +
			"\n" +
			"Self-contained templates are enabled because every template this profile\n" +
			"selects declares one; without it the profile runs nothing.",
		Config: map[string]any{
			"code":                  true,
			"tags":                  []any{"gcp-cloud-config"},
			"enable-self-contained": true,
		},
	},
	{
		Name: "k8s-cluster-security",
		Comment: "Nuclei scan profile for scanning aws ACLs\n" +
			"\n" +
			"Self-contained templates are enabled because every template this profile\n" +
			"selects declares one; without it the profile runs nothing.",
		Config: map[string]any{
			"code":                  true,
			"tags":                  []any{"k8s-cluster-security"},
			"enable-self-contained": true,
		},
	},
	{
		Name: "kev",
		Comment: "Nuclei Configuration Profile for CISA KEV Detection\n" +
			"This configuration file is specifically tailored for detecting Known Exploited Vulnerabilities (KEV) using Nuclei.\n" +
			"This profile is focused on identifying vulnerabilities that are listed in the Cybersecurity and Infrastructure Security Agency (CISA) Known Exploited Vulnerabilities (KEV) catalog.\n" +
			"Detecting KEVs is crucial for mitigating risks associated with known and actively exploited vulnerabilities.",
		Config: map[string]any{
			"tags": []any{"kev"},
		},
	},
	{
		Name: "misconfigurations",
		Comment: "Nuclei Configuration Profile for Misconfigurations Detection\n" +
			"This configuration file is specifically tailored for detecting misconfigurations using Nuclei.\n" +
			"This profile is focused on identifying various misconfigurations that can lead to security vulnerabilities. Detecting and correcting misconfigurations is essential for maintaining the security and integrity of systems and applications.",
		Config: map[string]any{
			"templates": []any{"http/misconfiguration/", "network/misconfig/", "javascript/misconfiguration/"},
		},
	},
	{
		Name: "osint",
		Comment: "Nuclei Configuration Profile for OSINT Detection\n" +
			"This configuration file is specifically tailored for detecting Open Source Intelligence (OSINT) related issues using Nuclei.\n" +
			"This profile is focused on identifying various OSINT-related security risks, including exposed information, backdoors, command and control servers, and more. OSINT scanning helps in gathering intelligence that could be used to identify potential threats and vulnerabilities.",
		Config: map[string]any{
			"tags":         []any{"osint", "honeypot", "backdoor", "c2", "osint-social", "exposures", "malware", "enum", "phishing"},
			"include-tags": []any{"phishing"},
		},
	},
	{
		Name: "pentest",
		Comment: "Nuclei Configuration Profile for Penetration Testing\n" +
			"This configuration file is specifically tailored for performing penetration testing using Nuclei.\n" +
			"This profile is focused on identifying security vulnerabilities across various protocols and services, including HTTP, TCP, JavaScript, DNS, and SSL. It excludes templates related to Denial of Service (DoS), fuzzing, and Open Source Intelligence (OSINT) to ensure focused and efficient penetration testing.",
		Config: map[string]any{
			"type":         []any{"http", "tcp", "javascript", "dns", "ssl"},
			"exclude-tags": []any{"dos", "fuzz", "osint"},
		},
	},
	{
		Name: "privilege-escalation",
		Comment: "Nuclei Configuration Profile for Local Privilege Escalation Vulnerabilities\n" +
			"This configuration file is specifically tailored for detecting local privilege escalation vulnerabilities using Nuclei.\n" +
			"This profile is focused on identifying vulnerabilities that can lead to local privilege escalation and local security issues. It includes code templates to enhance detection capabilities and targets specific scenarios where local vulnerabilities can be exploited for gaining higher privileges.\n" +
			"Included Templates:\n" +
			"This configuration references specific templates tagged with 'privesc' and 'local' to cover comprehensive detection of local privilege escalation vulnerabilities:\n" +
			"Configuration:\n" +
			"The profile includes code templates to check for local privilege escalation vulnerabilities.",
		Config: map[string]any{
			"code":         true,
			"tags":         []any{"privesc"},
			"include-tags": []any{"local"},
		},
	},
	{
		Name: "recommended",
		Comment: "Nuclei Configuration Profile for Recommended Detection\n" +
			"This configuration file is specifically tailored for performing recommended scans using Nuclei.\n" +
			"This profile is focused on identifying a wide range of security vulnerabilities across various protocols and services. It includes templates with different severity levels and excludes certain tags and template IDs to provide a balanced and focused detection approach.",
		Config: map[string]any{
			"severity":   []any{"critical", "high", "medium", "low", "unknown"},
			"type":       []any{"dns", "ssl", "tcp", "http", "javascript"},
			"exclude-id": []any{"CVE-2021-45967", "CVE-2021-36380", "CVE-2021-33544", "CVE-2021-32305", "CVE-2021-31755", "CVE-2021-28164", "CVE-2021-27931", "CVE-2021-26855", "CVE-2021-25052", "CVE-2021-1498", "CVE-2020-7796", "CVE-2020-5775", "CVE-2020-35713", "CVE-2020-26919", "CVE-2020-25223", "CVE-2020-24148", "CVE-2020-10770", "CVE-2019-9978", "CVE-2019-8451", "CVE-2019-3929", "CVE-2019-2767", "CVE-2019-2616", "CVE-2019-20224", "CVE-2019-19824", "CVE-2019-10758", "CVE-2018-16167", "CVE-2018-15517", "CVE-2018-1000600", "CVE-2017-9506", "CVE-2017-3506", "CVE-2017-18638", "CVE-2016-1555", "CVE-2015-8813", "CVE-2014-3206", "CVE-2009-4223", "CNVD-2021-09650", "generic-tokens", "credentials-disclosure", "targa-camera-ssrf", "cloudflare-external-image-resize", "linkerd-ssrf-detection", "ssrf-via-oauth-misconfig", "tls-sni-proxy", "xmlrpc-pingback-ssrf", "hashicorp-consul-rce", "mirai-unknown-rce", "optilink-ont1gew-gpon-rce", "sar2html-rce", "zimbra-preauth-ssrf", "wp-xmlrpc-pingback-detection", "fastjson-1-2-41-rce", "fastjson-1-2-42-rce", "fastjson-1-2-43-rce", "fastjson-1-2-62-rce", "fastjson-1-2-67-rce", "fastjson-1-2-68-rce", "request-based-interaction", "open-proxy-internal", "open-proxy-localhost", "open-proxy-portscan"},
		},
	},
	{
		Name: "subdomain-takeovers",
		Comment: "Nuclei Configuration Profile for Subdomain Takeover Detection\n" +
			"This configuration file is specifically tailored for detecting subdomain takeovers using Nuclei.\n" +
			"This profile is focused on identifying subdomain takeover vulnerabilities across different cloud service providers.\n" +
			"Subdomain takeovers can occur when a DNS entry points to a deprovisioned or unclaimed cloud resource, potentially\n" +
			"allowing an attacker to claim the resource and hijack the subdomain.",
		Config: map[string]any{
			"templates": []any{"http/takeovers/", "dns/azure-takeover-detection.yaml", "dns/elasticbeanstalk-takeover.yaml"},
		},
	},
	{
		Name: "windows-audit",
		Comment: "Nuclei Configuration Profile for Windows Audit\n" +
			"This configuration file is specifically tailored for auditing Windows environments using Nuclei.\n" +
			"This profile is focused on identifying misconfigurations and vulnerabilities in Windows systems. Ensuring proper configuration and security controls is crucial for protecting Windows environments and ensuring that only authorized entities have access.\n" +
			"Included Templates:\n" +
			"This configuration references specific templates tagged with 'windows-audit' to cover comprehensive scanning of Windows systems.",
		Config: map[string]any{
			"code": true,
			"tags": []any{"windows-audit"},
		},
	},
	{
		Name: "wordpress",
		Comment: "Nuclei Configuration Profile for WordPress Detection\n" +
			"This configuration file is specifically tailored for detecting vulnerabilities in WordPress installations using Nuclei.\n" +
			"This profile is focused on identifying security issues specific to WordPress, including vulnerable plugins, themes, and core components. Ensuring the security of WordPress installations is crucial due to its widespread use and common targeting by attackers.",
		Config: map[string]any{
			"tags": []any{"wordpress"},
		},
	},
}
