// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF Account object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

import "strconv"

// Account is the OCSF Account object. The Account object contains details about
// the account that initiated or performed a specific activity within a system
// or application. Additionally, the Account object refers to logical Cloud and
// Software-as-a-Service (SaaS) based containers such as AWS Accounts, Azure
// Subscriptions, Oracle Cloud Compartments, Google Cloud Projects, and
// otherwise.
//
// OCSF requires at least one of: name, uid. Validate enforces it, because no
// struct shape can.
type Account struct {
	// Labels. The list of labels associated to the account.
	// OCSF: labels (optional)
	Labels []string `json:"labels,omitempty"`

	// Name. The name of the account (e.g. GCP Project name , Linux Account name or
	// AWS Account name).
	// OCSF: name (recommended)
	Name string `json:"name,omitempty"`

	// Type. The account type, normalized to the caption of 'account_type_id'. In
	// the case of 'Other', it is defined by the event source.
	// OCSF: type (optional)
	Type string `json:"type,omitempty"`

	// Type ID. The normalized account type identifier.
	// OCSF: type_id (recommended)
	TypeID AccountTypeID `json:"type_id,omitempty"`

	// Unique ID. The unique identifier of the account (e.g. AWS Account ID , OCID
	// , GCP Project ID , Azure Subscription ID , Google Workspace Customer ID , or
	// M365 Tenant UID).
	// OCSF: uid (recommended)
	UID string `json:"uid,omitempty"`
}

// AccountTypeID is OCSF account.type_id. The normalized account type
// identifier.
type AccountTypeID int

const (
	// The account type is unknown.
	AccountTypeIDUnknown AccountTypeID = 0

	AccountTypeIDLDAPAccount AccountTypeID = 1

	AccountTypeIDWindowsAccount AccountTypeID = 2

	AccountTypeIDAWSIAMUser AccountTypeID = 3

	AccountTypeIDAWSIAMRole AccountTypeID = 4

	AccountTypeIDGCPAccount AccountTypeID = 5

	AccountTypeIDAzureADAccount AccountTypeID = 6

	AccountTypeIDMacOSAccount AccountTypeID = 7

	AccountTypeIDAppleAccount AccountTypeID = 8

	AccountTypeIDLinuxAccount AccountTypeID = 9

	AccountTypeIDAWSAccount AccountTypeID = 10

	AccountTypeIDGCPProject AccountTypeID = 11

	AccountTypeIDOCICompartment AccountTypeID = 12

	AccountTypeIDAzureSubscription AccountTypeID = 13

	AccountTypeIDSalesforceAccount AccountTypeID = 14

	AccountTypeIDGoogleWorkspace AccountTypeID = 15

	AccountTypeIDServicenowInstance AccountTypeID = 16

	AccountTypeIDM365Tenant AccountTypeID = 17

	AccountTypeIDEmailAccount AccountTypeID = 18

	// The account type is not mapped.
	AccountTypeIDOther AccountTypeID = 99
)

// String returns the caption OCSF publishes for the value, so a rendered
// AccountTypeID reads the way the schema browser shows it.
func (v AccountTypeID) String() string {
	switch v {
	case AccountTypeIDUnknown:
		return "Unknown"
	case AccountTypeIDLDAPAccount:
		return "LDAP Account"
	case AccountTypeIDWindowsAccount:
		return "Windows Account"
	case AccountTypeIDAWSIAMUser:
		return "AWS IAM User"
	case AccountTypeIDAWSIAMRole:
		return "AWS IAM Role"
	case AccountTypeIDGCPAccount:
		return "GCP Account"
	case AccountTypeIDAzureADAccount:
		return "Azure AD Account"
	case AccountTypeIDMacOSAccount:
		return "Mac OS Account"
	case AccountTypeIDAppleAccount:
		return "Apple Account"
	case AccountTypeIDLinuxAccount:
		return "Linux Account"
	case AccountTypeIDAWSAccount:
		return "AWS Account"
	case AccountTypeIDGCPProject:
		return "GCP Project"
	case AccountTypeIDOCICompartment:
		return "OCI Compartment"
	case AccountTypeIDAzureSubscription:
		return "Azure Subscription"
	case AccountTypeIDSalesforceAccount:
		return "Salesforce Account"
	case AccountTypeIDGoogleWorkspace:
		return "Google Workspace"
	case AccountTypeIDServicenowInstance:
		return "Servicenow Instance"
	case AccountTypeIDM365Tenant:
		return "M365 Tenant"
	case AccountTypeIDEmailAccount:
		return "Email Account"
	case AccountTypeIDOther:
		return "Other"
	}
	return "AccountTypeID(" + strconv.Itoa(int(v)) + ")"
}
