// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF Affected Software Package object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

import "strconv"

// AffectedPackage is the OCSF Affected Software Package object. The Affected
// Package object describes details about a software package identified as
// affected by a vulnerability/vulnerabilities.
type AffectedPackage struct {
	// Architecture. Architecture is a shorthand name describing the type of
	// computer hardware the packaged software is meant to run on.
	// OCSF: architecture (recommended)
	Architecture string `json:"architecture,omitempty"`

	// The product CPE identifier. The Common Platform Enumeration (CPE) name as
	// described by (<a target='_blank'
	// href='https://nvd.nist.gov/products/cpe'>NIST</a>) For example:
	// cpe:/a:apple:safari:16.2.
	// OCSF: cpe_name (optional)
	CPEName string `json:"cpe_name,omitempty"`

	// Epoch. The software package epoch. Epoch is a way to define weighted
	// dependencies based on version numbers.
	// OCSF: epoch (optional)
	Epoch int `json:"epoch,omitempty"`

	// Fixed In Version. The software package version in which a reported
	// vulnerability was patched/fixed.
	// OCSF: fixed_in_version (optional)
	FixedInVersion string `json:"fixed_in_version,omitempty"`

	// Software License. The software license applied to this package.
	// OCSF: license (optional)
	License string `json:"license,omitempty"`

	// Name. The software package name.
	// OCSF: name (required)
	Name string `json:"name"`

	// Package Manager. The software packager manager utilized to manage a package
	// on a system, e.g. npm, yum, dpkg etc.
	// OCSF: package_manager (optional)
	PackageManager string `json:"package_manager,omitempty"`

	// Path. The installation path of the affected package.
	// OCSF: path (optional)
	Path string `json:"path,omitempty"`

	// Package URL. A purl is a URL string used to identify and locate a software
	// package in a mostly universal and uniform way across programming languages,
	// package managers, packaging conventions, tools, APIs and databases.
	// OCSF: purl (optional)
	Purl string `json:"purl,omitempty"`

	// Software Release Details. Release is the number of times a version of the
	// software has been packaged.
	// OCSF: release (optional)
	Release string `json:"release,omitempty"`

	// Type. The type of software package, normalized to the caption of the type_id
	// value. In the case of 'Other', it is defined by the source.
	// OCSF: type (optional)
	Type string `json:"type,omitempty"`

	// Type ID. The type of software package.
	// OCSF: type_id (recommended)
	TypeID AffectedPackageTypeID `json:"type_id,omitempty"`

	// Vendor Name. The name of the vendor who published the software package.
	// OCSF: vendor_name (optional)
	VendorName string `json:"vendor_name,omitempty"`

	// Version. The software package version.
	// OCSF: version (required)
	Version string `json:"version"`
}

// AffectedPackageTypeID is OCSF affected_package.type_id. The type of software
// package.
type AffectedPackageTypeID int

const (
	// The type is unknown.
	AffectedPackageTypeIDUnknown AffectedPackageTypeID = 0

	// An application software package.
	AffectedPackageTypeIDApplication AffectedPackageTypeID = 1

	// An operating system software package.
	AffectedPackageTypeIDOperatingSystem AffectedPackageTypeID = 2

	// The type is not mapped. See the type attribute, which contains a data source
	// specific value.
	AffectedPackageTypeIDOther AffectedPackageTypeID = 99
)

// String returns the caption OCSF publishes for the value, so a rendered
// AffectedPackageTypeID reads the way the schema browser shows it.
func (v AffectedPackageTypeID) String() string {
	switch v {
	case AffectedPackageTypeIDUnknown:
		return "Unknown"
	case AffectedPackageTypeIDApplication:
		return "Application"
	case AffectedPackageTypeIDOperatingSystem:
		return "Operating System"
	case AffectedPackageTypeIDOther:
		return "Other"
	}
	return "AffectedPackageTypeID(" + strconv.Itoa(int(v)) + ")"
}
