// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF Cloud object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

// Cloud is the OCSF Cloud object. The Cloud object contains information about a
// cloud or Software-as-a-Service account or similar construct, such as AWS
// Account ID, regions, organizations, folders, compartments, tenants, etc.
type Cloud struct {
	// Account. The account object describes details about the account that was the
	// source or target of the activity.
	// OCSF: account (optional)
	Account *Account `json:"account,omitempty"`

	// Cloud Partition. The canonical cloud partition name to which the region is
	// assigned (e.g. AWS Partitions: aws, aws-cn, aws-us-gov).
	// OCSF: cloud_partition (optional)
	CloudPartition string `json:"cloud_partition,omitempty"`

	// Organization. Organization and org unit relevant to the event or object.
	// OCSF: org (optional)
	Org *Organization `json:"org,omitempty"`

	// Project ID. The unique identifier of a Cloud project.
	// OCSF: project_uid (optional)
	ProjectUID string `json:"project_uid,omitempty"`

	// Provider. The unique name of the Cloud services provider, such as AWS, MS
	// Azure, GCP, etc.
	// OCSF: provider (required)
	Provider string `json:"provider"`

	// Region. The name of the cloud region, as defined by the cloud provider.
	// OCSF: region (recommended)
	Region string `json:"region,omitempty"`

	// Cloud Availability Zone. The availability zone in the cloud region, as
	// defined by the cloud provider.
	// OCSF: zone (optional)
	Zone string `json:"zone,omitempty"`
}
