// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF CVE object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

// CVE is the OCSF CVE object. The Common Vulnerabilities and Exposures (CVE)
// object represents publicly disclosed cybersecurity vulnerabilities defined in
// CVE Program catalog (<a target='_blank'
// href='https://cve.mitre.org/'>CVE</a>). There is one CVE Record for each
// vulnerability in the catalog.
type CVE struct {
	// Created Time. The Record Creation Date identifies when the CVE ID was issued
	// to a CVE Numbering Authority (CNA) or the CVE Record was published on the
	// CVE List. Note that the Record Creation Date does not necessarily indicate
	// when this vulnerability was discovered, shared with the affected vendor,
	// publicly disclosed, or updated in CVE.
	// OCSF: created_time (recommended)
	CreatedTime int64 `json:"created_time,omitempty"`

	// CVSS Score. The CVSS object details Common Vulnerability Scoring System (<a
	// target='_blank' href='https://www.first.org/cvss/'>CVSS</a>) scores from the
	// advisory that are related to the vulnerability.
	// OCSF: cvss (recommended)
	CVSS []CVSS `json:"cvss,omitempty"`

	// CWE. The CWE object represents a weakness in a software system that can be
	// exploited by a threat actor to perform an attack. The CWE object is based on
	// the <a target='_blank' href='https://cwe.mitre.org/'>Common Weakness
	// Enumeration (CWE)</a> catalog.
	// OCSF: cwe (optional)
	CWE *CWE `json:"cwe,omitempty"`

	// CWE UID. The <a target='_blank' href='https://cwe.mitre.org/'>Common
	// Weakness Enumeration (CWE)</a> unique identifier. For example: CWE-787.
	// OCSF: cwe_uid (optional)
	CWEUID string `json:"cwe_uid,omitempty"`

	// CWE URL. Common Weakness Enumeration (CWE) definition URL. For example:
	// https://cwe.mitre.org/data/definitions/787.html.
	// OCSF: cwe_url (optional)
	CWEURL string `json:"cwe_url,omitempty"`

	// Description. A brief description of the CVE Record.
	// OCSF: desc (optional)
	Desc string `json:"desc,omitempty"`

	// EPSS. The Exploit Prediction Scoring System (EPSS) object describes the
	// estimated probability a vulnerability will be exploited. EPSS is a
	// community-driven effort to combine descriptive information about
	// vulnerabilities (CVEs) with evidence of actual exploitation in-the-wild. (<a
	// target='_blank' href='https://www.first.org/epss/'>EPSS</a>).
	// OCSF: epss (optional)
	EPSS *EPSS `json:"epss,omitempty"`

	// Modified Time. The Record Modified Date identifies when the CVE record was
	// last updated.
	// OCSF: modified_time (optional)
	ModifiedTime int64 `json:"modified_time,omitempty"`

	// References. A list of reference URLs with additional information about the
	// CVE Record.
	// OCSF: references (recommended)
	References []string `json:"references,omitempty"`

	// Title. A title or a brief phrase summarizing the CVE record.
	// OCSF: title (recommended)
	Title string `json:"title,omitempty"`

	// Vulnerability Type. The vulnerability type as selected from a large dropdown
	// menu during CVE refinement. Most frequently used vulnerability types are:
	// DoS, Code Execution, Overflow, Memory Corruption, Sql Injection, XSS,
	// Directory Traversal, Http Response Splitting, Bypass something, Gain
	// Information, Gain Privileges, CSRF, File Inclusion. For more information see
	// <a target='_blank'
	// href='https://www.cvedetails.com/vulnerabilities-by-types.php'>Vulnerabilities
	// By Type</a> distributions.
	// OCSF: type (recommended)
	Type string `json:"type,omitempty"`

	// CVE ID. The Common Vulnerabilities and Exposures unique number assigned to a
	// specific computer vulnerability. A CVE Identifier begins with 4 digits
	// representing the year followed by a sequence of digits that acts as a unique
	// identifier. For example: CVE-2021-12345.
	// OCSF: uid (required)
	UID string `json:"uid"`
}
