// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF CVSS Score object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

// CVSS is the OCSF CVSS Score object. The Common Vulnerability Scoring System
// (<a target='_blank' href='https://www.first.org/cvss/'>CVSS</a>) object
// provides a way to capture the principal characteristics of a vulnerability
// and produce a numerical score reflecting its severity.
type CVSS struct {
	// Base Score. The CVSS base score. For example: 9.1.
	// OCSF: base_score (required)
	BaseScore float64 `json:"base_score"`

	// CVSS Depth. The CVSS depth represents a depth of the equation used to
	// calculate CVSS score.
	// OCSF: depth (recommended)
	Depth string `json:"depth,omitempty"`

	// Overall Score. The CVSS overall score, impacted by base, temporal, and
	// environmental metrics. For example: 9.1.
	// OCSF: overall_score (recommended)
	OverallScore float64 `json:"overall_score,omitempty"`

	// Severity. The Common Vulnerability Scoring System (CVSS) Qualitative
	// Severity Rating. A textual representation of the numeric score. <strong>CVSS
	// v2.0</strong> Low (0.0 – 3.9) Medium (4.0 – 6.9) High (7.0 – 10.0)
	// <strong>CVSS v3.0</strong> None (0.0) Low (0.1 - 3.9) Medium (4.0 - 6.9)
	// High (7.0 - 8.9) Critical (9.0 - 10.0)
	// OCSF: severity (optional)
	Severity string `json:"severity,omitempty"`

	// Source URL. The source URL for the CVSS score. For example:
	// https://nvd.nist.gov/vuln/detail/CVE-2021-44228
	// OCSF: src_url (optional)
	SrcURL string `json:"src_url,omitempty"`

	// Vector String. The CVSS vector string is a text representation of a set of
	// CVSS metrics. It is commonly used to record or transfer CVSS metric
	// information in a concise form. For example:
	// 3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:H.
	// OCSF: vector_string (optional)
	VectorString string `json:"vector_string,omitempty"`

	// Vendor Name. The vendor that provided the CVSS score. For example: NVD,
	// REDHAT etc.
	// OCSF: vendor_name (recommended)
	VendorName string `json:"vendor_name,omitempty"`

	// Version. The CVSS version. For example: 3.1.
	// OCSF: version (required)
	Version string `json:"version"`
}
