// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF CWE object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

// CWE is the OCSF CWE object. The CWE object represents a weakness in a
// software system that can be exploited by a threat actor to perform an attack.
// The CWE object is based on the <a target='_blank'
// href='https://cwe.mitre.org/'>Common Weakness Enumeration (CWE)</a> catalog.
type CWE struct {
	// Caption. The caption assigned to the Common Weakness Enumeration unique
	// identifier.
	// OCSF: caption (optional)
	Caption string `json:"caption,omitempty"`

	// Source URL. URL pointing to the CWE Specification. For more information see
	// <a target='_blank' href='https://cwe.mitre.org/'>CWE.</a>
	// OCSF: src_url (optional)
	SrcURL string `json:"src_url,omitempty"`

	// CWE ID. The Common Weakness Enumeration unique number assigned to a specific
	// weakness. A CWE Identifier begins "CWE" followed by a sequence of digits
	// that acts as a unique identifier. For example: CWE-123.
	// OCSF: uid (required)
	UID string `json:"uid"`
}
