// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF Detection Finding class, pruned to the attributes recon populates.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

import "strconv"

// DetectionFinding is OCSF class 2004 in category 2. A Detection Finding
// describes detections or alerts generated by security products using
// correlation engines, detection engines or other methodologies. Note: if the
// event producer is a security control, the security_control profile should be
// applied and its attacks information, if present, should be duplicated into
// the finding_info object. <strong>Note: </strong>If the Finding is an
// incident, i.e. requires incident workflow, also apply the incident profile or
// aggregate this finding into an Incident Finding.
type DetectionFinding struct {
	// Activity ID. The normalized identifier of the finding activity.
	// OCSF: activity_id (required)
	ActivityID ActivityID `json:"activity_id"`

	// Activity. The finding activity name, as defined by the activity_id.
	// OCSF: activity_name (optional)
	ActivityName string `json:"activity_name,omitempty"`

	// Category. The event category name, as defined by category_uid value:
	// Findings.
	// OCSF: category_name (optional)
	CategoryName string `json:"category_name,omitempty"`

	// Category ID. The category unique identifier of the event.
	// OCSF: category_uid (required)
	CategoryUID int `json:"category_uid"`

	// Class. The event class name, as defined by class_uid value: Detection
	// Finding.
	// OCSF: class_name (optional)
	ClassName string `json:"class_name,omitempty"`

	// Class ID. The unique identifier of a class. A class describes the attributes
	// available in an event.
	// OCSF: class_uid (required)
	ClassUID int `json:"class_uid"`

	// Cloud. Describes details about the Cloud environment where the event was
	// originally created or logged.
	// OCSF: cloud (required, under profile cloud)
	Cloud *Cloud `json:"cloud,omitempty"`

	// Evidence Artifacts. Describes various evidence artifacts associated to the
	// activity/activities that triggered a security detection.
	// OCSF: evidences (recommended)
	Evidences []Evidences `json:"evidences,omitempty"`

	// Finding Information. Describes the supporting information about a generated
	// finding.
	// OCSF: finding_info (required)
	FindingInfo *FindingInfo `json:"finding_info"`

	// Impact. The impact , normalized to the caption of the impact_id value. In
	// the case of 'Other', it is defined by the event source.
	// OCSF: impact (optional)
	Impact string `json:"impact,omitempty"`

	// Impact ID. The normalized impact of the incident or finding. Per NIST, this
	// is the magnitude of harm that can be expected to result from the
	// consequences of unauthorized disclosure, modification, destruction, or loss
	// of information or information system availability.
	// OCSF: impact_id (optional)
	ImpactID ImpactID `json:"impact_id,omitempty"`

	// Alert. Indicates that the event is considered to be an alertable signal. For
	// example, an activity_id of 'Create' could constitute an alertable signal and
	// the value would be true, while 'Close' likely would not and either omit the
	// attribute or set its value to false. Note that other events with the
	// security_control profile may also be deemed alertable signals and may also
	// carry is_alert = true attributes.
	// OCSF: is_alert (recommended)
	IsAlert bool `json:"is_alert,omitempty"`

	// Message. The description of the event/finding, as defined by the source.
	// OCSF: message (recommended)
	Message string `json:"message,omitempty"`

	// Metadata. The metadata associated with the event or a finding.
	// OCSF: metadata (required)
	Metadata *Metadata `json:"metadata"`

	// Observables. The observables associated with the event or a finding.
	// OCSF: observables (recommended)
	Observables []Observable `json:"observables,omitempty"`

	// Remediation Guidance. Describes the recommended remediation steps to address
	// identified issue(s).
	// OCSF: remediation (optional)
	Remediation *Remediation `json:"remediation,omitempty"`

	// Affected Resources. Describes details about resources that were the target
	// of the activity that triggered the finding.
	// OCSF: resources (recommended)
	Resources []ResourceDetails `json:"resources,omitempty"`

	// Risk Details. Describes the risk associated with the finding.
	// OCSF: risk_details (optional)
	RiskDetails string `json:"risk_details,omitempty"`

	// Severity. The event/finding severity, normalized to the caption of the
	// severity_id value. In the case of 'Other', it is defined by the source.
	// OCSF: severity (optional)
	Severity string `json:"severity,omitempty"`

	// Severity ID. The normalized identifier of the event/finding severity. The
	// normalized severity is a measurement the effort and expense required to
	// manage and resolve an event or incident. Smaller numerical values represent
	// lower impact events, and larger numerical values represent higher impact
	// events.
	// OCSF: severity_id (required)
	SeverityID SeverityID `json:"severity_id"`

	// Status. The normalized status of the Finding set by the consumer normalized
	// to the caption of the status_id value. In the case of 'Other', it is defined
	// by the source.
	// OCSF: status (optional)
	Status string `json:"status,omitempty"`

	// Status Code. The event status code, as reported by the event source.<br
	// /><br />For example, in a Windows Failed Authentication event, this would be
	// the value of 'Failure Code', e.g. 0x18.
	// OCSF: status_code (recommended)
	StatusCode string `json:"status_code,omitempty"`

	// Status Detail. The status detail contains additional information about the
	// event/finding outcome.
	// OCSF: status_detail (recommended)
	StatusDetail string `json:"status_detail,omitempty"`

	// Status ID. The normalized status identifier of the Finding, set by the
	// consumer.
	// OCSF: status_id (recommended)
	StatusID StatusID `json:"status_id,omitempty"`

	// Event Time. The normalized event occurrence time or the finding creation
	// time.
	// OCSF: time (required)
	Time int64 `json:"time"`

	// Type Name. The event/finding type name, as defined by the type_uid.
	// OCSF: type_name (optional)
	TypeName string `json:"type_name,omitempty"`

	// Type ID. The event/finding type ID. It identifies the event's semantics and
	// structure. The value is calculated by the logging system as: class_uid * 100
	// + activity_id.
	// OCSF: type_uid (required)
	TypeUID int64 `json:"type_uid"`

	// Unmapped Data. The attributes that are not mapped to the event schema. The
	// names and values of those attributes are specific to the event source.
	// OCSF: unmapped (optional)
	Unmapped map[string]any `json:"unmapped,omitempty"`

	// Vulnerabilities. Describes vulnerabilities reported in a Detection Finding.
	// OCSF: vulnerabilities (optional)
	Vulnerabilities []Vulnerability `json:"vulnerabilities,omitempty"`
}

// ActivityID is OCSF detection_finding.activity_id. The normalized identifier
// of the finding activity.
type ActivityID int

const (
	// The event activity is unknown.
	ActivityIDUnknown ActivityID = 0

	// A finding was created.
	ActivityIDCreate ActivityID = 1

	// A finding was updated.
	ActivityIDUpdate ActivityID = 2

	// A finding was closed.
	ActivityIDClose ActivityID = 3

	// The event activity is not mapped. See the activity_name attribute, which
	// contains a data source specific value.
	ActivityIDOther ActivityID = 99
)

// String returns the caption OCSF publishes for the value, so a rendered
// ActivityID reads the way the schema browser shows it.
func (v ActivityID) String() string {
	switch v {
	case ActivityIDUnknown:
		return "Unknown"
	case ActivityIDCreate:
		return "Create"
	case ActivityIDUpdate:
		return "Update"
	case ActivityIDClose:
		return "Close"
	case ActivityIDOther:
		return "Other"
	}
	return "ActivityID(" + strconv.Itoa(int(v)) + ")"
}

// ImpactID is OCSF detection_finding.impact_id. The normalized impact of the
// incident or finding. Per NIST, this is the magnitude of harm that can be
// expected to result from the consequences of unauthorized disclosure,
// modification, destruction, or loss of information or information system
// availability.
type ImpactID int

const (
	// The normalized impact is unknown.
	ImpactIDUnknown ImpactID = 0

	// The magnitude of harm is low.
	ImpactIDLow ImpactID = 1

	// The magnitude of harm is moderate.
	ImpactIDMedium ImpactID = 2

	// The magnitude of harm is high.
	ImpactIDHigh ImpactID = 3

	// The magnitude of harm is high and the scope is widespread.
	ImpactIDCritical ImpactID = 4

	// The impact is not mapped. See the impact attribute, which contains a data
	// source specific value.
	ImpactIDOther ImpactID = 99
)

// String returns the caption OCSF publishes for the value, so a rendered
// ImpactID reads the way the schema browser shows it.
func (v ImpactID) String() string {
	switch v {
	case ImpactIDUnknown:
		return "Unknown"
	case ImpactIDLow:
		return "Low"
	case ImpactIDMedium:
		return "Medium"
	case ImpactIDHigh:
		return "High"
	case ImpactIDCritical:
		return "Critical"
	case ImpactIDOther:
		return "Other"
	}
	return "ImpactID(" + strconv.Itoa(int(v)) + ")"
}

// SeverityID is OCSF detection_finding.severity_id. The normalized identifier
// of the event/finding severity. The normalized severity is a measurement the
// effort and expense required to manage and resolve an event or incident.
// Smaller numerical values represent lower impact events, and larger numerical
// values represent higher impact events.
type SeverityID int

const (
	// The event/finding severity is unknown.
	SeverityIDUnknown SeverityID = 0

	// Informational message. No action required.
	SeverityIDInformational SeverityID = 1

	// The user decides if action is needed.
	SeverityIDLow SeverityID = 2

	// Action is required but the situation is not serious at this time.
	SeverityIDMedium SeverityID = 3

	// Action is required immediately.
	SeverityIDHigh SeverityID = 4

	// Action is required immediately and the scope is broad.
	SeverityIDCritical SeverityID = 5

	// An error occurred but it is too late to take remedial action.
	SeverityIDFatal SeverityID = 6

	// The event/finding severity is not mapped. See the severity attribute, which
	// contains a data source specific value.
	SeverityIDOther SeverityID = 99
)

// String returns the caption OCSF publishes for the value, so a rendered
// SeverityID reads the way the schema browser shows it.
func (v SeverityID) String() string {
	switch v {
	case SeverityIDUnknown:
		return "Unknown"
	case SeverityIDInformational:
		return "Informational"
	case SeverityIDLow:
		return "Low"
	case SeverityIDMedium:
		return "Medium"
	case SeverityIDHigh:
		return "High"
	case SeverityIDCritical:
		return "Critical"
	case SeverityIDFatal:
		return "Fatal"
	case SeverityIDOther:
		return "Other"
	}
	return "SeverityID(" + strconv.Itoa(int(v)) + ")"
}

// StatusID is OCSF detection_finding.status_id. The normalized status
// identifier of the Finding, set by the consumer.
type StatusID int

const (
	// The status is unknown.
	StatusIDUnknown StatusID = 0

	// The Finding is new and yet to be reviewed.
	StatusIDNew StatusID = 1

	// The Finding is under review.
	StatusIDInProgress StatusID = 2

	// The Finding was reviewed, determined to be benign or a false positive and is
	// now suppressed.
	StatusIDSuppressed StatusID = 3

	// The Finding was reviewed, remediated and is now considered resolved.
	StatusIDResolved StatusID = 4

	// The Finding was archived.
	StatusIDArchived StatusID = 5

	// The event status is not mapped. See the status attribute, which contains a
	// data source specific value.
	StatusIDOther StatusID = 99
)

// String returns the caption OCSF publishes for the value, so a rendered
// StatusID reads the way the schema browser shows it.
func (v StatusID) String() string {
	switch v {
	case StatusIDUnknown:
		return "Unknown"
	case StatusIDNew:
		return "New"
	case StatusIDInProgress:
		return "In Progress"
	case StatusIDSuppressed:
		return "Suppressed"
	case StatusIDResolved:
		return "Resolved"
	case StatusIDArchived:
		return "Archived"
	case StatusIDOther:
		return "Other"
	}
	return "StatusID(" + strconv.Itoa(int(v)) + ")"
}
