// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF EPSS object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

// EPSS is the OCSF EPSS object. The Exploit Prediction Scoring System (EPSS)
// object describes the estimated probability a vulnerability will be exploited.
// EPSS is a community-driven effort to combine descriptive information about
// vulnerabilities (CVEs) with evidence of actual exploitation in-the-wild. (<a
// target='_blank' href='https://www.first.org/epss/'>EPSS</a>).
type EPSS struct {
	// Created Time. The timestamp indicating when the EPSS score was calculated.
	// OCSF: created_time (recommended)
	CreatedTime int64 `json:"created_time,omitempty"`

	// EPSS Percentile. The EPSS score's percentile representing relative
	// importance and ranking of the score in the larger EPSS dataset.
	// OCSF: percentile (optional)
	Percentile float64 `json:"percentile,omitempty"`

	// EPPS Score. The EPSS score representing the probability [0-1] of
	// exploitation in the wild in the next 30 days (following score publication).
	// OCSF: score (required)
	Score string `json:"score"`

	// Version. The version of the EPSS model used to calculate the score.
	// OCSF: version (recommended)
	Version string `json:"version,omitempty"`
}
