// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF Evidence Artifacts object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

import "encoding/json"

// Evidences is the OCSF Evidence Artifacts object. A collection of evidence
// artifacts associated to the activity/activities that triggered a security
// detection.
//
// OCSF requires at least one of: data, dst_endpoint, src_endpoint, url.
// Validate enforces it, because no struct shape can.
type Evidences struct {
	// Data. Additional evidence data that is not accounted for in the specific
	// evidence attributes. Use only when absolutely necessary.
	// OCSF: data (optional)
	Data json.RawMessage `json:"data,omitempty"`

	// Destination Endpoint. Describes details about the destination of the network
	// activity that triggered the detection.
	// OCSF: dst_endpoint (recommended)
	DstEndpoint *NetworkEndpoint `json:"dst_endpoint,omitempty"`

	// HTTP Request. Describes details about the http request associated to the
	// activity that triggered the detection.
	// OCSF: http_request (recommended)
	HTTPRequest *HTTPRequest `json:"http_request,omitempty"`

	// HTTP Response. Describes details about the http response associated to the
	// activity that triggered the detection.
	// OCSF: http_response (recommended)
	HTTPResponse *HTTPResponse `json:"http_response,omitempty"`

	// Name. The naming convention or type identifier of the evidence associated
	// with the security detection. For example, the @odata.type from Microsoft
	// Graph Alerts V2 or display_name from CrowdStrike Falcon Incident Behaviors.
	// OCSF: name (optional)
	Name string `json:"name,omitempty"`

	// Cloud Resources. Describes details about the cloud resources directly
	// related to activity that triggered the detection. For resources impacted by
	// the detection, use Affected Resources at the top-level of the finding.
	// OCSF: resources (recommended)
	Resources []ResourceDetails `json:"resources,omitempty"`

	// Source Endpoint. Describes details about the source of the network activity
	// that triggered the detection.
	// OCSF: src_endpoint (recommended)
	SrcEndpoint *NetworkEndpoint `json:"src_endpoint,omitempty"`

	// Unique ID. The unique identifier of the evidence associated with the
	// security detection. For example, the activity_id from CrowdStrike Falcon
	// Alerts or behavior_id from CrowdStrike Falcon Incident Behaviors.
	// OCSF: uid (optional)
	UID string `json:"uid,omitempty"`

	// URL. The URL object that pertains to the event or object associated to the
	// activity that triggered the detection.
	// OCSF: url (recommended)
	URL *URL `json:"url,omitempty"`
}
