// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF Finding Information object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

// FindingInfo is the OCSF Finding Information object. The Finding Information
// object describes metadata related to a security finding generated by a
// security tool or system.
type FindingInfo struct {
	// Created Time. The time when the finding was created.
	// OCSF: created_time (optional)
	CreatedTime int64 `json:"created_time,omitempty"`

	// Data Sources. A list of data sources utilized in generation of the finding.
	// OCSF: data_sources (optional)
	DataSources []string `json:"data_sources,omitempty"`

	// Description. The description of the reported finding.
	// OCSF: desc (optional)
	Desc string `json:"desc,omitempty"`

	// First Seen. The time when the finding was first observed. e.g. The time when
	// a vulnerability was first observed. It can differ from the created_time
	// timestamp, which reflects the time this finding was created.
	// OCSF: first_seen_time (optional)
	FirstSeenTime int64 `json:"first_seen_time,omitempty"`

	// Last Seen. The time when the finding was most recently observed. e.g. The
	// time when a vulnerability was most recently observed. It can differ from the
	// modified_time timestamp, which reflects the time this finding was last
	// modified.
	// OCSF: last_seen_time (optional)
	LastSeenTime int64 `json:"last_seen_time,omitempty"`

	// Modified Time. The time when the finding was last modified.
	// OCSF: modified_time (optional)
	ModifiedTime int64 `json:"modified_time,omitempty"`

	// Source URL. The URL pointing to the source of the finding.
	// OCSF: src_url (optional)
	SrcURL string `json:"src_url,omitempty"`

	// Title. A title or a brief phrase summarizing the reported finding.
	// OCSF: title (recommended)
	Title string `json:"title,omitempty"`

	// Types. One or more types of the reported finding.
	// OCSF: types (optional)
	Types []string `json:"types,omitempty"`

	// Unique ID. The unique identifier of the reported finding.
	// OCSF: uid (required)
	UID string `json:"uid"`

	// Alternate ID. The alternative unique identifier of the reported finding.
	// OCSF: uid_alt (optional)
	UIDAlt string `json:"uid_alt,omitempty"`
}
