// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF Group object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

// Group is the OCSF Group object. The Group object represents a collection or
// association of entities, such as users, policies, or devices. It serves as a
// logical grouping mechanism to organize and manage entities with similar
// characteristics or permissions within a system or organization, including but
// not limited to purposes of access control.
//
// OCSF requires at least one of: name, uid. Validate enforces it, because no
// struct shape can.
type Group struct {
	// Description. The group description.
	// OCSF: desc (optional)
	Desc string `json:"desc,omitempty"`

	// Domain. The domain where the group is defined. For example: the LDAP or
	// Active Directory domain.
	// OCSF: domain (optional)
	Domain string `json:"domain,omitempty"`

	// Name. The group name.
	// OCSF: name (recommended)
	Name string `json:"name,omitempty"`

	// Privileges. The group privileges.
	// OCSF: privileges (optional)
	Privileges []string `json:"privileges,omitempty"`

	// Account Type. The type of the group or account.
	// OCSF: type (optional)
	Type string `json:"type,omitempty"`

	// Unique ID. The unique identifier of the group. For example, for Windows
	// events this is the security identifier (SID) of the group.
	// OCSF: uid (recommended)
	UID string `json:"uid,omitempty"`
}
