// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF HTTP Request object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

// HTTPRequest is the OCSF HTTP Request object. The HTTP Request object
// represents the attributes of a request made to a web server. It encapsulates
// the details and metadata associated with an HTTP request, including the
// request method, headers, URL, query parameters, body content, and other
// relevant information.
type HTTPRequest struct {
	// HTTP Arguments. The arguments sent along with the HTTP request.
	// OCSF: args (optional)
	Args string `json:"args,omitempty"`

	// Request Body Length. The actual length of the HTTP request body, in number
	// of bytes, independent of a potentially existing Content-Length header.
	// OCSF: body_length (optional)
	BodyLength int `json:"body_length,omitempty"`

	// HTTP Headers. Additional HTTP headers of an HTTP request or response.
	// OCSF: http_headers (recommended)
	HTTPHeaders []HTTPHeader `json:"http_headers,omitempty"`

	// HTTP Method. The <a target='_blank'
	// href='https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods'>HTTP
	// request method</a> indicates the desired action to be performed for a given
	// resource.
	// OCSF: http_method (recommended)
	HTTPMethod string `json:"http_method,omitempty"`

	// Request Length. The length of the entire HTTP request, in number of bytes.
	// OCSF: length (optional)
	Length int `json:"length,omitempty"`

	// HTTP Referrer. The request header that identifies the address of the
	// previous web page, which is linked to the current web page or resource being
	// requested.
	// OCSF: referrer (optional)
	Referrer string `json:"referrer,omitempty"`

	// Unique ID. The unique identifier of the http request.
	// OCSF: uid (optional)
	UID string `json:"uid,omitempty"`

	// URL. The URL object that pertains to the request.
	// OCSF: url (recommended)
	URL *URL `json:"url,omitempty"`

	// HTTP User-Agent. The request header that identifies the operating system and
	// web browser.
	// OCSF: user_agent (recommended)
	UserAgent string `json:"user_agent,omitempty"`

	// HTTP Version. The Hypertext Transfer Protocol (HTTP) version.
	// OCSF: version (recommended)
	Version string `json:"version,omitempty"`

	// X-Forwarded-For. The X-Forwarded-For header identifying the originating IP
	// address(es) of a client connecting to a web server through an HTTP proxy or
	// a load balancer.
	// OCSF: x_forwarded_for (optional)
	XForwardedFor []string `json:"x_forwarded_for,omitempty"`
}
