// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF HTTP Response object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

// HTTPResponse is the OCSF HTTP Response object. The HTTP Response object
// contains detailed information about the response sent from a web server to
// the requester. It encompasses attributes and metadata that describe the
// response status, headers, body content, and other relevant information.
type HTTPResponse struct {
	// Response Body Length. The actual length of the HTTP response body, in number
	// of bytes, independent of a potentially existing Content-Length header.
	// OCSF: body_length (optional)
	BodyLength int `json:"body_length,omitempty"`

	// Response Code. The Hypertext Transfer Protocol (HTTP) status code returned
	// from the web server to the client. For example, 200.
	// OCSF: code (required)
	Code int `json:"code"`

	// HTTP Content Type. The request header that identifies the original <a
	// target='_blank'
	// href='https://www.iana.org/assignments/media-types/media-types.xhtml'>media
	// type </a> of the resource (prior to any content encoding applied for
	// sending).
	// OCSF: content_type (optional)
	ContentType string `json:"content_type,omitempty"`

	// HTTP Headers. Additional HTTP headers of an HTTP request or response.
	// OCSF: http_headers (recommended)
	HTTPHeaders []HTTPHeader `json:"http_headers,omitempty"`

	// Latency. The HTTP response latency measured in milliseconds.
	// OCSF: latency (optional)
	Latency int `json:"latency,omitempty"`

	// Response Length. The length of the entire HTTP response, in number of bytes.
	// OCSF: length (optional)
	Length int `json:"length,omitempty"`

	// Message. The description of the event/finding, as defined by the source.
	// OCSF: message (optional)
	Message string `json:"message,omitempty"`

	// Status. The response status. For example: A successful HTTP status of 'OK'
	// which corresponds to a code of 200.
	// OCSF: status (optional)
	Status string `json:"status,omitempty"`
}
