// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF HTTP Header object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

// HTTPHeader is the OCSF HTTP Header object. The HTTP Header object represents
// the headers sent in an HTTP request or response. HTTP headers are key-value
// pairs that convey additional information about the HTTP message, including
// details about the content, caching, authentication, encoding, and other
// aspects of the communication.
type HTTPHeader struct {
	// Name. The name of the HTTP header.
	// OCSF: name (required)
	Name string `json:"name"`

	// Value. The value of the HTTP header.
	// OCSF: value (required)
	Value string `json:"value"`
}
