// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF Metadata object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

// Metadata is the OCSF Metadata object. The Metadata object describes the
// metadata associated with the event.
type Metadata struct {
	// Correlation UID. The unique identifier used to correlate events.
	// OCSF: correlation_uid (optional)
	CorrelationUID string `json:"correlation_uid,omitempty"`

	// Event Code. The Event ID, Code, or Name that the product uses to primarily
	// identify the event.
	// OCSF: event_code (optional)
	EventCode string `json:"event_code,omitempty"`

	// Labels. The list of labels attached to the event. For example: ["sample",
	// "dev"]
	// OCSF: labels (optional)
	Labels []string `json:"labels,omitempty"`

	// Logged Time. The time when the logging system collected and logged the
	// event. This attribute is distinct from the event time in that event time
	// typically contain the time extracted from the original event. Most of the
	// time, these two times will be different.
	// OCSF: logged_time (optional)
	LoggedTime int64 `json:"logged_time,omitempty"`

	// Original Time. The original event time as reported by the event source. For
	// example, the time in the original format from system event log such as
	// Syslog on Unix/Linux and the System event file on Windows. Omit if event is
	// generated instead of collected via logs.
	// OCSF: original_time (recommended)
	OriginalTime string `json:"original_time,omitempty"`

	// Product. The product that reported the event.
	// OCSF: product (required)
	Product *Product `json:"product"`

	// Profiles. The list of profiles used to create the event. Profiles should be
	// referenced by their name attribute for core profiles, or extension/name for
	// profiles from extensions.
	// OCSF: profiles (optional)
	Profiles []string `json:"profiles,omitempty"`

	// Event UID. The logging system-assigned unique identifier of an event
	// instance.
	// OCSF: uid (optional)
	UID string `json:"uid,omitempty"`

	// Version. The version of the OCSF schema, using Semantic Versioning
	// Specification (<a target='_blank' href='https://semver.org'>SemVer</a>). For
	// example: 1.0.0. Event consumers use the version to determine the available
	// event attributes.
	// OCSF: version (required)
	Version string `json:"version"`
}
