// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF Network Endpoint object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

import "strconv"

// NetworkEndpoint is the OCSF Network Endpoint object. The Network Endpoint
// object describes characteristics of a network endpoint. These can be a source
// or destination of a network connection.
//
// OCSF requires at least one of: domain, hostname, ip, name, svc_name, uid.
// Validate enforces it, because no struct shape can.
type NetworkEndpoint struct {
	// Domain. The name of the domain that the endpoint belongs to or that
	// corresponds to the endpoint.
	// OCSF: domain (optional)
	Domain string `json:"domain,omitempty"`

	// Hostname. The fully qualified name of the endpoint.
	// OCSF: hostname (recommended)
	Hostname string `json:"hostname,omitempty"`

	// IP Address. The IP address of the endpoint, in either IPv4 or IPv6 format.
	// OCSF: ip (recommended)
	IP string `json:"ip,omitempty"`

	// Name. The short name of the endpoint.
	// OCSF: name (recommended)
	Name string `json:"name,omitempty"`

	// Port. The port used for communication within the network connection.
	// OCSF: port (recommended)
	Port int `json:"port,omitempty"`

	// Service Name. The service name in service-to-service connections. For
	// example, AWS VPC logs the pkt-src-aws-service and pkt-dst-aws-service fields
	// identify the connection is coming from or going to an AWS service.
	// OCSF: svc_name (recommended)
	SvcName string `json:"svc_name,omitempty"`

	// Type. The network endpoint type. For example: unknown, server, desktop,
	// laptop, tablet, mobile, virtual, browser, or other.
	// OCSF: type (optional)
	Type string `json:"type,omitempty"`

	// Type ID. The network endpoint type ID.
	// OCSF: type_id (recommended)
	TypeID NetworkEndpointTypeID `json:"type_id,omitempty"`

	// Unique ID. The unique identifier of the endpoint.
	// OCSF: uid (recommended)
	UID string `json:"uid,omitempty"`
}

// NetworkEndpointTypeID is OCSF network_endpoint.type_id. The network endpoint
// type ID.
type NetworkEndpointTypeID int

const (
	// The type is unknown.
	NetworkEndpointTypeIDUnknown NetworkEndpointTypeID = 0

	// A <a target='_blank'
	// href='https://d3fend.mitre.org/dao/artifact/d3f:Server/'>server</a>.
	NetworkEndpointTypeIDServer NetworkEndpointTypeID = 1

	// A <a target='_blank'
	// href='https://d3fend.mitre.org/dao/artifact/d3f:DesktopComputer/'>desktop
	// computer</a>.
	NetworkEndpointTypeIDDesktop NetworkEndpointTypeID = 2

	// A <a target='_blank'
	// href='https://d3fend.mitre.org/dao/artifact/d3f:LaptopComputer/'>laptop
	// computer</a>.
	NetworkEndpointTypeIDLaptop NetworkEndpointTypeID = 3

	// A <a target='_blank'
	// href='https://d3fend.mitre.org/dao/artifact/d3f:TabletComputer/'>tablet
	// computer</a>.
	NetworkEndpointTypeIDTablet NetworkEndpointTypeID = 4

	// A <a target='_blank'
	// href='https://d3fend.mitre.org/dao/artifact/d3f:MobilePhone/'>mobile
	// phone</a>.
	NetworkEndpointTypeIDMobile NetworkEndpointTypeID = 5

	// A <a target='_blank'
	// href='https://d3fend.mitre.org/dao/artifact/d3f:VirtualizationSoftware/'>virtual
	// machine</a>.
	NetworkEndpointTypeIDVirtual NetworkEndpointTypeID = 6

	// An <a target='_blank'
	// href='https://www.techtarget.com/iotagenda/definition/IoT-device'>IOT
	// (Internet of Things) device</a>.
	NetworkEndpointTypeIDIOT NetworkEndpointTypeID = 7

	// A <a target='_blank'
	// href='https://d3fend.mitre.org/dao/artifact/d3f:Browser/'>web browser</a>.
	NetworkEndpointTypeIDBrowser NetworkEndpointTypeID = 8

	// A <a target='_blank'
	// href='https://d3fend.mitre.org/dao/artifact/d3f:Firewall/'>networking
	// firewall</a>.
	NetworkEndpointTypeIDFirewall NetworkEndpointTypeID = 9

	// A <a target='_blank'
	// href='https://d3fend.mitre.org/dao/artifact/d3f:Switch/'>networking
	// switch</a>.
	NetworkEndpointTypeIDSwitch NetworkEndpointTypeID = 10

	// A <a target='_blank'
	// href='https://en.wikipedia.org/wiki/Ethernet_hub'>networking hub</a>.
	NetworkEndpointTypeIDHub NetworkEndpointTypeID = 11

	// A <a target='_blank'
	// href='https://d3fend.mitre.org/dao/artifact/d3f:Router/'>networking
	// router</a>.
	NetworkEndpointTypeIDRouter NetworkEndpointTypeID = 12

	// An <a target='_blank'
	// href='https://d3fend.mitre.org/dao/artifact/d3f:IntrusionDetectionSystem/'>intrusion
	// detection system</a>.
	NetworkEndpointTypeIDIDS NetworkEndpointTypeID = 13

	// An <a target='_blank'
	// href='https://d3fend.mitre.org/dao/artifact/d3f:IntrusionPreventionSystem/'>intrusion
	// prevention system</a>.
	NetworkEndpointTypeIDIPS NetworkEndpointTypeID = 14

	// A <a target='_blank'
	// href='https://en.wikipedia.org/wiki/Load_balancing_(computing)'>Load
	// Balancer device.</a>
	NetworkEndpointTypeIDLoadBalancer NetworkEndpointTypeID = 15

	// The type is not mapped. See the type attribute, which contains a data source
	// specific value.
	NetworkEndpointTypeIDOther NetworkEndpointTypeID = 99
)

// String returns the caption OCSF publishes for the value, so a rendered
// NetworkEndpointTypeID reads the way the schema browser shows it.
func (v NetworkEndpointTypeID) String() string {
	switch v {
	case NetworkEndpointTypeIDUnknown:
		return "Unknown"
	case NetworkEndpointTypeIDServer:
		return "Server"
	case NetworkEndpointTypeIDDesktop:
		return "Desktop"
	case NetworkEndpointTypeIDLaptop:
		return "Laptop"
	case NetworkEndpointTypeIDTablet:
		return "Tablet"
	case NetworkEndpointTypeIDMobile:
		return "Mobile"
	case NetworkEndpointTypeIDVirtual:
		return "Virtual"
	case NetworkEndpointTypeIDIOT:
		return "IOT"
	case NetworkEndpointTypeIDBrowser:
		return "Browser"
	case NetworkEndpointTypeIDFirewall:
		return "Firewall"
	case NetworkEndpointTypeIDSwitch:
		return "Switch"
	case NetworkEndpointTypeIDHub:
		return "Hub"
	case NetworkEndpointTypeIDRouter:
		return "Router"
	case NetworkEndpointTypeIDIDS:
		return "IDS"
	case NetworkEndpointTypeIDIPS:
		return "IPS"
	case NetworkEndpointTypeIDLoadBalancer:
		return "Load Balancer"
	case NetworkEndpointTypeIDOther:
		return "Other"
	}
	return "NetworkEndpointTypeID(" + strconv.Itoa(int(v)) + ")"
}
