// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF Observable object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

import "strconv"

// Observable is the OCSF Observable object. The observable object is a pivot
// element that contains related information found in many places in the event.
type Observable struct {
	// Name. The full name of the observable attribute. The name is a
	// pointer/reference to an attribute within the OCSF event data. For example:
	// file.name.
	// OCSF: name (recommended)
	Name string `json:"name,omitempty"`

	// Type. The observable value type name.
	// OCSF: type (optional)
	Type string `json:"type,omitempty"`

	// Type ID. The observable value type identifier.
	// OCSF: type_id (required)
	TypeID ObservableTypeID `json:"type_id"`

	// Value. The value associated with the observable attribute. The meaning of
	// the value depends on the observable type. If the name refers to a scalar
	// attribute, then the value is the value of the attribute. If the name refers
	// to an object attribute, then the value is not populated.
	// OCSF: value (optional)
	Value string `json:"value,omitempty"`
}

// ObservableTypeID is OCSF observable.type_id. The observable value type
// identifier.
type ObservableTypeID int

const (
	// Unknown observable data type.
	ObservableTypeIDUnknown ObservableTypeID = 0

	// Observable by Dictionary Type. Unique name assigned to a device connected to
	// a computer network. It may be a fully qualified domain name (FQDN). For
	// example: r2-d2.example.com., mx.example.com
	ObservableTypeIDHostname ObservableTypeID = 1

	// Observable by Dictionary Type. Internet Protocol address (IP address), in
	// either IPv4 or IPv6 format. For example: 192.168.200.24,
	// 2001:0db8:85a3:0000:0000:8a2e:0370:7334.
	ObservableTypeIDIPAddress ObservableTypeID = 2

	// Observable by Dictionary Type. Media Access Control (MAC) address. For
	// example: 18:36:F3:98:4F:9A.
	ObservableTypeIDMACAddress ObservableTypeID = 3

	// Observable by Dictionary Type. User name. For example: john_doe.
	ObservableTypeIDUserName ObservableTypeID = 4

	// Observable by Dictionary Type. Email address. For example:
	// john_doe@example.com.
	ObservableTypeIDEmailAddress ObservableTypeID = 5

	// Observable by Dictionary Type. Uniform Resource Locator (URL) string. For
	// example: http://www.example.com/download/trouble.exe.
	ObservableTypeIDURLString ObservableTypeID = 6

	// Observable by Dictionary Type. File name. For example: text-file.txt.
	ObservableTypeIDFileName ObservableTypeID = 7

	// Observable by Dictionary Type. Hash. A unique value that corresponds to the
	// content of the file, image, ja3_hash or hassh found in the schema. For
	// example: MD5: 3172ac7e2b55cbb81f04a6e65855a628.
	ObservableTypeIDHash ObservableTypeID = 8

	// Observable by Dictionary Type. Process name. For example: Notepad.
	ObservableTypeIDProcessName ObservableTypeID = 9

	// Observable by Dictionary Type. Resource unique identifier. For example, S3
	// Bucket name or EC2 Instance ID.
	ObservableTypeIDResourceUID ObservableTypeID = 10

	// Observable by Dictionary Type. The TCP/UDP port number. For example: 80, 22.
	ObservableTypeIDPort ObservableTypeID = 11

	// Observable by Dictionary Type. The subnet represented in a CIDR notation,
	// using the format network_address/prefix_length. The network_address can be
	// in either IPv4 or IPv6 format. The prefix length indicates the number of
	// bits used for the network portion, and the remaining bits are available for
	// host addresses within that subnet. For example: 192.168.1.0/24,
	// 2001:0db8:85a3:0000::/64
	ObservableTypeIDSubnet ObservableTypeID = 12

	// Observable by Dictionary Attribute. The full command line used to launch an
	// application, service, process, or job. For example: ssh user@10.0.0.10. If
	// the command line is unavailable or missing, the empty string '' is to be
	// used.
	ObservableTypeIDCommandLine ObservableTypeID = 13

	// Observable by Dictionary Attribute. The ISO 3166-1 Alpha-2 country
	// code.Note: The two letter country code should be capitalized. For example:
	// US or CA.
	ObservableTypeIDCountry ObservableTypeID = 14

	// Observable by Dictionary Attribute. The process identifier, as reported by
	// the operating system. Process ID (PID) is a number used by the operating
	// system to uniquely identify an active process.
	ObservableTypeIDProcessID ObservableTypeID = 15

	// Observable by Dictionary Attribute. The request header that identifies the
	// operating system and web browser.
	ObservableTypeIDHTTPUserAgent ObservableTypeID = 16

	// Observable by Object-Specific Attribute. Object-specific attribute "uid" for
	// the CWE Object.
	ObservableTypeIDCWEObjectUid ObservableTypeID = 17

	// Observable by Object-Specific Attribute. Object-specific attribute "uid" for
	// the CVE Object.
	ObservableTypeIDCVEObjectUid ObservableTypeID = 18

	// Observable by Dictionary Attribute. The unique identifier of the user's
	// credential. For example, AWS Access Key ID.
	ObservableTypeIDUserCredentialID ObservableTypeID = 19

	// Observable by Object. The Endpoint object describes a physical or virtual
	// device that connects to and exchanges information with a computer network.
	// Some examples of endpoints are mobile devices, desktop computers, virtual
	// machines, embedded devices, and servers. Internet-of-Things devices—like
	// cameras, lighting, refrigerators, security systems, smart speakers, and
	// thermostats—are also endpoints.
	ObservableTypeIDEndpoint ObservableTypeID = 20

	// Observable by Object. The User object describes the characteristics of a
	// user/person or a security principal.
	ObservableTypeIDUser ObservableTypeID = 21

	// Observable by Object. The Email object describes the email metadata such as
	// sender, recipients, and direction, and can include embedded URLs and files.
	ObservableTypeIDEmail ObservableTypeID = 22

	// Observable by Object. The Uniform Resource Locator (URL) object describes
	// the characteristics of a URL.
	ObservableTypeIDUniformResourceLocator ObservableTypeID = 23

	// Observable by Object. The File object represents the metadata associated
	// with a file stored in a computer system. It encompasses information about
	// the file itself, including its attributes, properties, and organizational
	// details.
	ObservableTypeIDFile ObservableTypeID = 24

	// Observable by Object. The Process object describes a running instance of a
	// launched program.
	ObservableTypeIDProcess ObservableTypeID = 25

	// Observable by Object. The Geo Location object describes a geographical
	// location, usually associated with an IP address.
	ObservableTypeIDGeoLocation ObservableTypeID = 26

	// Observable by Object. The Container object describes an instance of a
	// specific container. A container is a prepackaged, portable system image that
	// runs isolated on an existing system using a container runtime like
	// containerd.
	ObservableTypeIDContainer ObservableTypeID = 27

	// Observable by Object. The registry key object describes a Windows registry
	// key.
	ObservableTypeIDRegistryKey ObservableTypeID = 28

	// Observable by Object. The registry value object describes a Windows registry
	// value.
	ObservableTypeIDRegistryValue ObservableTypeID = 29

	// Observable by Object. The Fingerprint object provides detailed information
	// about a digital fingerprint, which is a compact representation of data used
	// to identify a longer piece of information, such as a public key or file
	// content. It contains the algorithm and value of the fingerprint, enabling
	// efficient and reliable identification of the associated data.
	ObservableTypeIDFingerprint ObservableTypeID = 30

	// Observable by Object-Specific Attribute. Object-specific attribute "uid" for
	// the User Object.
	ObservableTypeIDUserObjectUid ObservableTypeID = 31

	// Observable by Object-Specific Attribute. Object-specific attribute "name"
	// for the Group Object.
	ObservableTypeIDGroupObjectName ObservableTypeID = 32

	// Observable by Object-Specific Attribute. Object-specific attribute "uid" for
	// the Group Object.
	ObservableTypeIDGroupObjectUid ObservableTypeID = 33

	// Observable by Object-Specific Attribute. Object-specific attribute "name"
	// for the Account Object.
	ObservableTypeIDAccountObjectName ObservableTypeID = 34

	// Observable by Object-Specific Attribute. Object-specific attribute "uid" for
	// the Account Object.
	ObservableTypeIDAccountObjectUid ObservableTypeID = 35

	// Observable by Dictionary Attribute. The script content, normalized to UTF-8
	// encoding irrespective of its original encoding. When emitting this
	// attribute, it may be appropriate to truncate large scripts. When consuming
	// this attribute, large scripts should be anticipated.
	ObservableTypeIDScriptContent ObservableTypeID = 36

	// Observable by Dictionary Attribute. The serial number that pertains to the
	// object. See specific usage.
	ObservableTypeIDSerialNumber ObservableTypeID = 37

	// Observable by Object-Specific Attribute. Object-specific attribute "name"
	// for the Resource Details Object.
	ObservableTypeIDResourceDetailsObjectName ObservableTypeID = 38

	// Observable by Object-Specific Attribute. Object-specific attribute "uid" for
	// the Process Entity Object.
	ObservableTypeIDProcessEntityObjectUid ObservableTypeID = 39

	// Observable by Object-Specific Attribute. Object-specific attribute "subject"
	// for the Email Object.
	ObservableTypeIDEmailObjectSubject ObservableTypeID = 40

	// Observable by Object-Specific Attribute. Object-specific attribute "uid" for
	// the Email Object.
	ObservableTypeIDEmailObjectUid ObservableTypeID = 41

	// Observable by Dictionary Attribute. The email header Message-ID value, as
	// defined by RFC 5322.
	ObservableTypeIDMessageUID ObservableTypeID = 42

	// Observable by Object-Specific Attribute. Object-specific attribute "name"
	// for the Registry Value Object.
	ObservableTypeIDRegistryValueObjectName ObservableTypeID = 43

	// Observable by Object-Specific Attribute. Object-specific attribute "uid" for
	// the Advisory Object.
	ObservableTypeIDAdvisoryObjectUid ObservableTypeID = 44

	// Observable by Dictionary Type. The full path to the file. For example: For
	// example: c:\windows\system32\svchost.exe.
	ObservableTypeIDFilePath ObservableTypeID = 45

	// Observable by Dictionary Type. Full path of registry key.
	ObservableTypeIDRegistryKeyPath ObservableTypeID = 46

	// The observable data type is not mapped. See the type attribute, which may
	// contain data source specific value.
	ObservableTypeIDOther ObservableTypeID = 99
)

// String returns the caption OCSF publishes for the value, so a rendered
// ObservableTypeID reads the way the schema browser shows it.
func (v ObservableTypeID) String() string {
	switch v {
	case ObservableTypeIDUnknown:
		return "Unknown"
	case ObservableTypeIDHostname:
		return "Hostname"
	case ObservableTypeIDIPAddress:
		return "IP Address"
	case ObservableTypeIDMACAddress:
		return "MAC Address"
	case ObservableTypeIDUserName:
		return "User Name"
	case ObservableTypeIDEmailAddress:
		return "Email Address"
	case ObservableTypeIDURLString:
		return "URL String"
	case ObservableTypeIDFileName:
		return "File Name"
	case ObservableTypeIDHash:
		return "Hash"
	case ObservableTypeIDProcessName:
		return "Process Name"
	case ObservableTypeIDResourceUID:
		return "Resource UID"
	case ObservableTypeIDPort:
		return "Port"
	case ObservableTypeIDSubnet:
		return "Subnet"
	case ObservableTypeIDCommandLine:
		return "Command Line"
	case ObservableTypeIDCountry:
		return "Country"
	case ObservableTypeIDProcessID:
		return "Process ID"
	case ObservableTypeIDHTTPUserAgent:
		return "HTTP User-Agent"
	case ObservableTypeIDCWEObjectUid:
		return "CWE Object: uid"
	case ObservableTypeIDCVEObjectUid:
		return "CVE Object: uid"
	case ObservableTypeIDUserCredentialID:
		return "User Credential ID"
	case ObservableTypeIDEndpoint:
		return "Endpoint"
	case ObservableTypeIDUser:
		return "User"
	case ObservableTypeIDEmail:
		return "Email"
	case ObservableTypeIDUniformResourceLocator:
		return "Uniform Resource Locator"
	case ObservableTypeIDFile:
		return "File"
	case ObservableTypeIDProcess:
		return "Process"
	case ObservableTypeIDGeoLocation:
		return "Geo Location"
	case ObservableTypeIDContainer:
		return "Container"
	case ObservableTypeIDRegistryKey:
		return "Registry Key"
	case ObservableTypeIDRegistryValue:
		return "Registry Value"
	case ObservableTypeIDFingerprint:
		return "Fingerprint"
	case ObservableTypeIDUserObjectUid:
		return "User Object: uid"
	case ObservableTypeIDGroupObjectName:
		return "Group Object: name"
	case ObservableTypeIDGroupObjectUid:
		return "Group Object: uid"
	case ObservableTypeIDAccountObjectName:
		return "Account Object: name"
	case ObservableTypeIDAccountObjectUid:
		return "Account Object: uid"
	case ObservableTypeIDScriptContent:
		return "Script Content"
	case ObservableTypeIDSerialNumber:
		return "Serial Number"
	case ObservableTypeIDResourceDetailsObjectName:
		return "Resource Details Object: name"
	case ObservableTypeIDProcessEntityObjectUid:
		return "Process Entity Object: uid"
	case ObservableTypeIDEmailObjectSubject:
		return "Email Object: subject"
	case ObservableTypeIDEmailObjectUid:
		return "Email Object: uid"
	case ObservableTypeIDMessageUID:
		return "Message UID"
	case ObservableTypeIDRegistryValueObjectName:
		return "Registry Value Object: name"
	case ObservableTypeIDAdvisoryObjectUid:
		return "Advisory Object: uid"
	case ObservableTypeIDFilePath:
		return "File Path"
	case ObservableTypeIDRegistryKeyPath:
		return "Registry Key Path"
	case ObservableTypeIDOther:
		return "Other"
	}
	return "ObservableTypeID(" + strconv.Itoa(int(v)) + ")"
}
