// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF Organization object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

// Organization is the OCSF Organization object. The Organization object
// describes characteristics of an organization or company and its division if
// any. Additionally, it also describes cloud and Software-as-a-Service (SaaS)
// logical hierarchies such as AWS Organizations, Google Cloud Organizations,
// Oracle Cloud Tenancies, and similar constructs.
//
// OCSF requires at least one of: name, uid. Validate enforces it, because no
// struct shape can.
type Organization struct {
	// Name. The name of the organization, Oracle Cloud Tenancy, Google Cloud
	// Organization, or AWS Organization. For example, Widget, Inc. or the AWS
	// Organization name .
	// OCSF: name (recommended)
	Name string `json:"name,omitempty"`

	// Org Unit Name. The name of an organizational unit, Google Cloud Folder, or
	// AWS Org Unit. For example, the GCP Project Name , or Dev_Prod_OU .
	// OCSF: ou_name (recommended)
	OUName string `json:"ou_name,omitempty"`

	// Org Unit ID. The unique identifier of an organizational unit, Google Cloud
	// Folder, or AWS Org Unit. For example, an Oracle Cloud Tenancy ID , AWS OU ID
	// , or GCP Folder ID .
	// OCSF: ou_uid (optional)
	OUUID string `json:"ou_uid,omitempty"`

	// Unique ID. The unique identifier of the organization, Oracle Cloud Tenancy,
	// Google Cloud Organization, or AWS Organization. For example, an AWS Org ID
	// or Oracle Cloud Domain ID .
	// OCSF: uid (recommended)
	UID string `json:"uid,omitempty"`
}
