// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF Product object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

// Product is the OCSF Product object. The Product object describes
// characteristics of a software product.
//
// OCSF requires at least one of: name, uid. Validate enforces it, because no
// struct shape can.
type Product struct {
	// Name. The name of the product.
	// OCSF: name (recommended)
	Name string `json:"name,omitempty"`

	// Unique ID. The unique identifier of the product.
	// OCSF: uid (recommended)
	UID string `json:"uid,omitempty"`

	// Vendor Name. The name of the vendor of the product.
	// OCSF: vendor_name (recommended)
	VendorName string `json:"vendor_name,omitempty"`

	// Version. The version of the product, as defined by the event source. For
	// example: 2013.1.3-beta.
	// OCSF: version (recommended)
	Version string `json:"version,omitempty"`
}
