// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF Remediation object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

// Remediation is the OCSF Remediation object. The Remediation object describes
// the recommended remediation steps to address identified issue(s).
type Remediation struct {
	// Description. The description of the remediation strategy.
	// OCSF: desc (required)
	Desc string `json:"desc"`

	// References. A list of supporting URL/s, references that help describe the
	// remediation strategy.
	// OCSF: references (optional)
	References []string `json:"references,omitempty"`
}
