// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF Resource Details object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

import "encoding/json"

// ResourceDetails is the OCSF Resource Details object. The Resource Details
// object describes details about resources that were affected by the
// activity/event.
//
// OCSF requires at least one of: name, uid. Validate enforces it, because no
// struct shape can.
type ResourceDetails struct {
	// Cloud Partition. The canonical cloud partition name to which the region is
	// assigned (e.g. AWS Partitions: aws, aws-cn, aws-us-gov).
	// OCSF: cloud_partition (optional, under profile cloud)
	CloudPartition string `json:"cloud_partition,omitempty"`

	// Criticality. The criticality of the resource as defined by the event source.
	// OCSF: criticality (optional)
	Criticality string `json:"criticality,omitempty"`

	// Data. Additional data describing the resource.
	// OCSF: data (optional)
	Data json.RawMessage `json:"data,omitempty"`

	// Group. The name of the related resource group.
	// OCSF: group (optional)
	Group *Group `json:"group,omitempty"`

	// Hostname. The fully qualified name of the resource.
	// OCSF: hostname (recommended)
	Hostname string `json:"hostname,omitempty"`

	// IP Address. The IP address of the resource, in either IPv4 or IPv6 format.
	// OCSF: ip (recommended)
	IP string `json:"ip,omitempty"`

	// Labels. The list of labels associated to the resource.
	// OCSF: labels (optional)
	Labels []string `json:"labels,omitempty"`

	// Name. The name of the resource.
	// OCSF: name (recommended)
	Name string `json:"name,omitempty"`

	// Namespace. The namespace is useful when similar entities exist that you need
	// to keep separate.
	// OCSF: namespace (optional)
	Namespace string `json:"namespace,omitempty"`

	// Region. The cloud region of the resource.
	// OCSF: region (optional, under profile cloud)
	Region string `json:"region,omitempty"`

	// Type. The resource type as defined by the event source.
	// OCSF: type (optional)
	Type string `json:"type,omitempty"`

	// Unique ID. The unique identifier of the resource.
	// OCSF: uid (recommended)
	UID string `json:"uid,omitempty"`

	// Alternate ID. The alternative unique identifier of the resource.
	// OCSF: uid_alt (optional)
	UIDAlt string `json:"uid_alt,omitempty"`

	// Version. The version of the resource. For example 1.2.3.
	// OCSF: version (optional)
	Version string `json:"version,omitempty"`

	// Cloud Availability Zone. The specific availability zone within a cloud
	// region where the resource is located.
	// OCSF: zone (optional, under profile cloud)
	Zone string `json:"zone,omitempty"`
}
