// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The class identity, requirement levels and object constraints Validate reads.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

// Version is the OCSF release these types were generated from.
const Version = "1.5.0"

const (
	// ClassUID identifies Detection Finding. OCSF composes it as category_uid*1000
	// plus the class's own uid.
	ClassUID = 2004

	// CategoryUID identifies the Findings category.
	CategoryUID = 2
)

// TypeUID composes the OCSF type identifier, which narrows a class to one
// activity. OCSF defines it as class_uid*100 plus the activity id.
func TypeUID(activity ActivityID) int64 {
	return int64(ClassUID)*100 + int64(activity)
}

// Profiles are the OCSF profiles Detection Finding may declare. A profile is
// what raises an attribute's requirement level, so which ones a record declares
// in metadata.profiles decides what Validate demands of it.
var Profiles = []string{
	"cloud",
	"container",
	"data_classification",
	"datetime",
	"host",
	"incident",
	"linux/linux_users",
	"osint",
	"security_control",
}

// Requirement is what OCSF asks of one attribute.
//
// Profile is empty when the requirement is unconditional, and names a profile
// when it applies only to a record that declares it: cloud is optional on a
// bare detection finding and required on one that audits a cloud account.
type Requirement struct {
	Attribute string
	Level     string
	Profile   string
}

// Requirements is the requirement level of every attribute these types carry.
var Requirements = []Requirement{
	{Attribute: "activity_id", Level: "required", Profile: ""},
	{Attribute: "activity_name", Level: "optional", Profile: ""},
	{Attribute: "category_name", Level: "optional", Profile: ""},
	{Attribute: "category_uid", Level: "required", Profile: ""},
	{Attribute: "class_name", Level: "optional", Profile: ""},
	{Attribute: "class_uid", Level: "required", Profile: ""},
	{Attribute: "cloud", Level: "required", Profile: "cloud"},
	{Attribute: "evidences", Level: "recommended", Profile: ""},
	{Attribute: "finding_info", Level: "required", Profile: ""},
	{Attribute: "impact", Level: "optional", Profile: ""},
	{Attribute: "impact_id", Level: "optional", Profile: ""},
	{Attribute: "is_alert", Level: "recommended", Profile: ""},
	{Attribute: "message", Level: "recommended", Profile: ""},
	{Attribute: "metadata", Level: "required", Profile: ""},
	{Attribute: "observables", Level: "recommended", Profile: ""},
	{Attribute: "remediation", Level: "optional", Profile: ""},
	{Attribute: "resources", Level: "recommended", Profile: ""},
	{Attribute: "risk_details", Level: "optional", Profile: ""},
	{Attribute: "severity", Level: "optional", Profile: ""},
	{Attribute: "severity_id", Level: "required", Profile: ""},
	{Attribute: "status", Level: "optional", Profile: ""},
	{Attribute: "status_code", Level: "recommended", Profile: ""},
	{Attribute: "status_detail", Level: "recommended", Profile: ""},
	{Attribute: "status_id", Level: "recommended", Profile: ""},
	{Attribute: "time", Level: "required", Profile: ""},
	{Attribute: "type_name", Level: "optional", Profile: ""},
	{Attribute: "type_uid", Level: "required", Profile: ""},
	{Attribute: "unmapped", Level: "optional", Profile: ""},
	{Attribute: "vulnerabilities", Level: "optional", Profile: ""},
}

// Constraint is a condition OCSF states about an object that a struct shape
// cannot express, so Validate checks it instead.
type Constraint struct {
	AtLeastOne []string
	JustOne    []string
}

// Constraints holds those conditions, keyed by OCSF object name. Only
// attributes these generated types actually carry appear: a constraint naming a
// pruned attribute would reject records that are in fact valid.
var Constraints = map[string]Constraint{
	"account":          {AtLeastOne: []string{"name", "uid"}},
	"evidences":        {AtLeastOne: []string{"data", "dst_endpoint", "src_endpoint", "url"}},
	"group":            {AtLeastOne: []string{"name", "uid"}},
	"network_endpoint": {AtLeastOne: []string{"domain", "hostname", "ip", "name", "svc_name", "uid"}},
	"organization":     {AtLeastOne: []string{"name", "uid"}},
	"product":          {AtLeastOne: []string{"name", "uid"}},
	"resource_details": {AtLeastOne: []string{"name", "uid"}},
	"url":              {AtLeastOne: []string{"path", "url_string"}},
	"vulnerability":    {JustOne: []string{"cve", "cwe"}},
}

// ObjectNames maps each generated Go type to the OCSF object it represents, so
// Validate can find an object's constraints while walking a record. Generated
// rather than derived by lowercasing, because the two names diverge wherever an
// initialism or an extension prefix is involved.
var ObjectNames = map[string]string{
	"Account":          "account",
	"AffectedPackage":  "affected_package",
	"CVE":              "cve",
	"CVSS":             "cvss",
	"CWE":              "cwe",
	"Cloud":            "cloud",
	"DetectionFinding": "detection_finding",
	"EPSS":             "epss",
	"Evidences":        "evidences",
	"FindingInfo":      "finding_info",
	"Group":            "group",
	"HTTPHeader":       "http_header",
	"HTTPRequest":      "http_request",
	"HTTPResponse":     "http_response",
	"Metadata":         "metadata",
	"NetworkEndpoint":  "network_endpoint",
	"Observable":       "observable",
	"Organization":     "organization",
	"Product":          "product",
	"Remediation":      "remediation",
	"ResourceDetails":  "resource_details",
	"URL":              "url",
	"Vulnerability":    "vulnerability",
}
