// Code generated by hack/gen-ocsf. DO NOT EDIT.
//
// The OCSF Uniform Resource Locator object.
//
// Source: OCSF 1.5.0, class detection_finding (2004).
//
// Regenerate with:
//	go run ./hack/gen-ocsf

package ocsf

// URL is the OCSF Uniform Resource Locator object. The Uniform Resource Locator
// (URL) object describes the characteristics of a URL.
//
// OCSF requires at least one of: path, url_string. Validate enforces it,
// because no struct shape can.
type URL struct {
	// Domain. The domain portion of the URL. For example: example.com in
	// https://sub.example.com.
	// OCSF: domain (optional)
	Domain string `json:"domain,omitempty"`

	// Hostname. The URL host as extracted from the URL. For example:
	// www.example.com from www.example.com/download/trouble.
	// OCSF: hostname (recommended)
	Hostname string `json:"hostname,omitempty"`

	// Path. The URL path as extracted from the URL. For example: /download/trouble
	// from www.example.com/download/trouble.
	// OCSF: path (recommended)
	Path string `json:"path,omitempty"`

	// Port. The URL port. For example: 80.
	// OCSF: port (recommended)
	Port int `json:"port,omitempty"`

	// HTTP Query String. The query portion of the URL. For example: the query
	// portion of the URL http://www.example.com/search?q=bad&sort=date is
	// q=bad&sort=date.
	// OCSF: query_string (recommended)
	QueryString string `json:"query_string,omitempty"`

	// Scheme. The scheme portion of the URL. For example: http, https, ftp, or
	// sftp.
	// OCSF: scheme (recommended)
	Scheme string `json:"scheme,omitempty"`

	// Subdomain. The subdomain portion of the URL. For example: sub in
	// https://sub.example.com or sub2.sub1 in https://sub2.sub1.example.com.
	// OCSF: subdomain (optional)
	Subdomain string `json:"subdomain,omitempty"`

	// URL String. The URL string. See RFC 1738. For example:
	// http://www.example.com/download/trouble.exe. Note: The URL path should not
	// populate the URL string.
	// OCSF: url_string (recommended)
	URLString string `json:"url_string,omitempty"`
}
