package trivy

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/flanksource/recon/internal/engines/scan"
	"github.com/flanksource/recon/internal/mute"
)

var _ scan.Muter = Engine{}

// IgnoreFile is the exclusion list recon generates for a run.
//
// Trivy's own name for it, in the run's scratch directory, so an operator who
// opens the artifact directory finds a file trivy itself would accept.
const IgnoreFile = ".trivyignore"

// Pushdown writes the checks trivy can decline to run into its ignore file.
//
// A file rather than a flag because trivy has no per-id exclusion flag, and the
// path is handed to the runner rather than put in the profile: a profile that
// could name an ignore file would be a profile that could name any file, which
// is the property Prowler's argument policy protects and there is no reason for
// trivy to be weaker.
//
// The plain one-id-per-line format rather than the sectioned YAML: a rule names
// checks without saying whether each is a vulnerability, a misconfiguration, a
// secret or a licence, and the plain form applies to all of them — which is
// what the rule means.
func (Engine) Pushdown(request scan.PushdownRequest) (scan.Pushdown, error) {
	plan := scan.Pushdown{Plan: mute.Plan{PushedDown: map[string]string{}}}

	ids := map[string]bool{}
	for _, rule := range request.Rules {
		if rule.Pushable() != mute.DimensionTemplates {
			continue
		}
		expressible, ok := ignorableIDs(rule.Templates)
		if !ok {
			continue
		}
		for _, id := range expressible {
			ids[id] = true
		}
		plan.Plan.PushedDown[rule.Name] = "ignorefile"
	}

	if len(ids) == 0 {
		return plan, nil
	}

	path := filepath.Join(request.WorkDir, IgnoreFile)
	if err := writeIgnoreFile(path, ids); err != nil {
		return scan.Pushdown{}, err
	}
	plan.File = path
	return plan, nil
}

// ignorableIDs reports the ids trivy can be told to skip, and whether every
// pattern in the rule could be turned into one.
//
// All or nothing per rule: a partly pushed rule would stop some checks running
// while still matching others afterwards, and the ones it stopped would leave
// nothing behind to show what happened.
//
// Two shapes are refused. Trivy ignores by exact id, so a glob cannot be handed
// over even though the rule matches with one. And an id carrying a slash is one
// recon composed — `license/GPL-3.0` — whose trivy-side name is not what the
// rule says, so translating it here would be guessing.
func ignorableIDs(patterns []string) ([]string, bool) {
	ids := make([]string, 0, len(patterns))
	for _, pattern := range patterns {
		if strings.ContainsAny(pattern, "*?[") || strings.Contains(pattern, "/") {
			return nil, false
		}
		ids = append(ids, pattern)
	}
	return ids, len(ids) > 0
}

func writeIgnoreFile(path string, ids map[string]bool) error {
	sorted := make([]string, 0, len(ids))
	for id := range ids {
		sorted = append(sorted, id)
	}
	// Sorted so a re-run of the same configuration writes the same file, which
	// is what makes the artifact directory diffable.
	sort.Strings(sorted)

	lines := []string{"# Generated by recon from the mute rules in force for this run.", "# Edits are overwritten."}
	lines = append(lines, sorted...)

	if err := os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0o600); err != nil {
		return fmt.Errorf("write trivy ignore file: %w", err)
	}
	return nil
}
