// Code generated by hack/gen-catalog. DO NOT EDIT.
//
// Regenerate with:
//	pnpm --dir app exec tsx hack/dump-catalog.ts
//	go run ./hack/gen-catalog

package naabu

import "github.com/flanksource/recon/internal/engines"

// catalog is naabu's option catalog: what a profile for this engine may set.
var catalog = engines.Sections{
	{
		ID:          "ports",
		Title:       "Ports & targets",
		Description: "Choose the port range and bound broad scans of shared infrastructure.",
		SourceURL:   "https://github.com/projectdiscovery/naabu#usage",
		Properties: []engines.Field{
			{Key: "port", Property: engines.Property{Type: "string", Title: "Ports", Description: "Ports or ranges to scan, such as 80,443,8000-8100."}},
			{Key: "top-ports", Property: engines.Property{Type: "string", Title: "Top ports", Description: "Use Naabu's ranked port set.", Enum: []string{"100", "1000", "full"}}},
			{Key: "exclude-ports", Property: engines.Property{Type: "array", Title: "Excluded ports", Description: "Ports, ranges, or files excluded from the scan.", Items: &engines.Property{Type: "string"}}},
			{Key: "ports-file", Property: engines.Property{Type: "array", Title: "Port files", Description: "Files containing ports to scan.", Items: &engines.Property{Type: "string"}}},
			{Key: "port-threshold", Property: engines.Property{Type: "integer", Title: "Port threshold", Description: "Stop scanning a host after this many open ports are found.", MultipleOf: engines.Num(1), Minimum: engines.Num(1)}},
			{Key: "exclude-cdn", Property: engines.Property{Type: "boolean", Title: "Limit CDN scans", Description: "Scan only ports 80 and 443 when the address belongs to a known CDN or WAF."}},
			{Key: "display-cdn", Property: engines.Property{Type: "boolean", Title: "Show CDN", Description: "Include detected CDN details in results."}},
		},
	},
	{
		ID:          "network",
		Title:       "Network & services",
		Description: "Control address selection, scan transport, DNS, and service detection.",
		SourceURL:   "https://github.com/projectdiscovery/naabu#usage",
		Properties: []engines.Field{
			{Key: "scan-all-ips", Property: engines.Property{Type: "boolean", Title: "Scan every IP", Description: "Scan every address resolved for a hostname."}},
			{Key: "ip-version", Property: engines.Property{Type: "array", Title: "IP versions", Description: "IP versions included in the scan.", ArrayDisplay: "filter-pills", Items: &engines.Property{Enum: []string{"4", "6"}}}},
			{Key: "scan-type", Property: engines.Property{Type: "string", Title: "Scan type", Description: "CONNECT works without raw-socket privileges.", Enum: []string{"c", "s"}}},
			{Key: "r", Property: engines.Property{Type: "string", Title: "Resolvers", Description: "Comma-separated custom DNS resolvers or a resolver file."}},
			{Key: "service-discovery", Property: engines.Property{Type: "boolean", Title: "Service discovery", Description: "Identify services on open ports."}},
			{Key: "service-version", Property: engines.Property{Type: "boolean", Title: "Service versions", Description: "Identify service versions when probe data is available."}},
		},
	},
	{
		ID:          "performance",
		Title:       "Performance",
		Description: "Bound connection rate, concurrency, timeouts, retries, and verification.",
		SourceURL:   "https://github.com/projectdiscovery/naabu#usage",
		Properties: []engines.Field{
			{Key: "c", Property: engines.Property{Type: "integer", Title: "Workers", Description: "Internal worker count. Naabu defaults to 25.", MultipleOf: engines.Num(1), Minimum: engines.Num(1)}},
			{Key: "rate", Property: engines.Property{Type: "integer", Title: "Packets per second", Description: "Global scan rate limit.", MultipleOf: engines.Num(1), Minimum: engines.Num(1)}},
			{Key: "retries", Property: engines.Property{Type: "integer", Title: "Retries", Description: "Number of scan attempts per port.", MultipleOf: engines.Num(1), Minimum: engines.Num(1)}},
			{Key: "timeout", Property: engines.Property{Type: "string", Title: "Timeout", Description: "Port timeout such as 1s or 1500ms."}},
			{Key: "warm-up-time", Property: engines.Property{Type: "integer", Title: "Warm-up time", Description: "Seconds between scan phases.", MultipleOf: engines.Num(1), Minimum: engines.Num(0)}},
			{Key: "verify", Property: engines.Property{Type: "boolean", Title: "Verify ports", Description: "Confirm discovered ports with a TCP connection."}},
		},
	},
}
