package main

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// render emits the generated table. Sorted throughout, so re-running the
// generator against an unchanged upstream produces byte-identical output and
// --check means what it says.
func render(read catalogue) ([]byte, error) {
	var out strings.Builder

	out.WriteString(`// Code generated by hack/gen-configdb-identity. DO NOT EDIT.
//
// The vocabularies config-db stores config items under, read from its own
// source. Recon uses them to look a resource up in Mission Control's catalog;
// it never creates config items, so nothing here has to be able to mint one.

package configdb

// gcpTypeOverrides disambiguates a Cloud Asset Inventory asset type whose bare
// resource name would collide across services — Instance alone is a Compute VM,
// an AlloyDB instance and a Cloud SQL instance. Anything absent keeps the
// resource half of its asset type unchanged.
var gcpTypeOverrides = map[string]string{
`)
	keys := make([]string, 0, len(read.GCPOverrides))
	for key := range read.GCPOverrides {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		fmt.Fprintf(&out, "\t%s: %s,\n", strconv.Quote(key), strconv.Quote(read.GCPOverrides[key]))
	}
	out.WriteString("}\n\n")

	writeSet(&out, "awsTypes", read.AWSTypes,
		"awsTypes is config-db's AWS vocabulary, which is AWS Config's own resource\n"+
			"type strings used verbatim. A vocabulary rather than a rule because the list\n"+
			"has members no rule predicts: AWS::::Account carries an empty service segment,\n"+
			"and a volume is AWS::EBS::Volume where AWS Config itself says EC2.")

	writeSet(&out, "githubTypes", read.GitHubTypes,
		"githubTypes is config-db's GitHub vocabulary.")

	writeSet(&out, "scraperLessTypes", read.ScraperLess,
		"scraperLessTypes are stored with no scraper id, so config-db's own lookup drops\n"+
			"the scraper from its predicate for them. A caller that scoped by scraper here\n"+
			"would filter out exactly the rows it was looking for.")

	out.WriteString(`// githubTypeAliases maps the lowercased resource kinds an engine is likely to
// report onto config-db's own type. Only the unambiguous ones: a name recon
// cannot place gets no type rather than a plausible guess.
var githubTypeAliases = map[string]string{
`)
	for _, alias := range githubAliases(read.GitHubTypes) {
		fmt.Fprintf(&out, "\t%s: %s,\n", strconv.Quote(alias.from), strconv.Quote(alias.to))
	}
	out.WriteString("}\n")

	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

func writeSet(out *strings.Builder, name string, values []string, doc string) {
	for _, line := range strings.Split(doc, "\n") {
		fmt.Fprintf(out, "// %s\n", line)
	}
	fmt.Fprintf(out, "var %s = map[string]struct{}{\n", name)
	for _, value := range values {
		fmt.Fprintf(out, "\t%s: {},\n", strconv.Quote(value))
	}
	out.WriteString("}\n\n")
}

type alias struct{ from, to string }

// githubAliases derives the lowercased bare kind for each GitHub type, so a
// resource reported as `Repository` finds `GitHub::Repository`. Derived rather
// than hand-listed: a type added upstream picks up its alias automatically.
func githubAliases(types []string) []alias {
	var aliases []alias
	for _, configType := range types {
		_, kind, ok := strings.Cut(configType, "::")
		if !ok || kind == "" {
			continue
		}
		aliases = append(aliases, alias{from: strings.ToLower(kind), to: configType})
	}
	sort.Slice(aliases, func(i, j int) bool { return aliases[i].from < aliases[j].from })
	return aliases
}
