// Command gen-catalog turns the dumped TypeScript option catalogs into Go.
//
//	go run ./hack/gen-catalog
//
// The catalogs describe ~200 upstream flags across three tools. Retyping them
// would introduce typos that stay invisible until someone opens the Profiles
// form and finds a wrong bound or a missing enum value, so they are generated
// from internal/engines/testdata/catalog.json — which a test then asserts the
// generated Go still reproduces exactly.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// property mirrors one entry of a section's `properties` map.
type property struct {
	Type         string    `json:"type"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	Enum         []string  `json:"enum"`
	Items        *property `json:"items"`
	MultipleOf   *float64  `json:"multipleOf"`
	Minimum      *float64  `json:"minimum"`
	Maximum      *float64  `json:"maximum"`
	ArrayDisplay string    `json:"x-array-display"`
}

type section struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	SourceURL   string `json:"sourceUrl"`
	// Properties is decoded through json.RawMessage so key order can be
	// recovered: a Go map would lose it, and order is the form layout.
	Properties json.RawMessage `json:"properties"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := moduleRoot()
	if err != nil {
		return err
	}

	raw, err := os.ReadFile(filepath.Join(root, "internal/engines/testdata/catalog.json"))
	if err != nil {
		return fmt.Errorf("read catalog: %w (run `pnpm --dir app exec tsx hack/dump-catalog.ts` first)", err)
	}

	var catalogs map[string][]section
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&catalogs); err != nil {
		return fmt.Errorf("decode catalog: %w", err)
	}

	engines := make([]string, 0, len(catalogs))
	for name := range catalogs {
		engines = append(engines, name)
	}
	sort.Strings(engines)

	for _, engine := range engines {
		target, err := targetFile(root, engine)
		if err != nil {
			return err
		}
		source, err := render(engine, catalogs[engine])
		if err != nil {
			return fmt.Errorf("render %s: %w", engine, err)
		}
		if err := os.WriteFile(target, source, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", target, err)
		}
		fmt.Printf("%-8s %2d sections -> %s\n", engine, len(catalogs[engine]),
			mustRel(root, target))
	}
	return nil
}

// targetFile places each catalog next to its engine implementation.
func targetFile(root, engine string) (string, error) {
	kinds := map[string]string{
		"nuclei": "scan",
		"httpx":  "discovery",
		"naabu":  "discovery",
	}
	kind, ok := kinds[engine]
	if !ok {
		return "", fmt.Errorf("no package mapping for engine %s", engine)
	}
	dir := filepath.Join(root, "internal/engines", kind, engine)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	return filepath.Join(dir, "catalog_generated.go"), nil
}

func render(engine string, sections []section) ([]byte, error) {
	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by hack/gen-catalog. DO NOT EDIT.\n")
	fmt.Fprintf(&out, "//\n")
	fmt.Fprintf(&out, "// Regenerate with:\n")
	fmt.Fprintf(&out, "//\tpnpm --dir app exec tsx hack/dump-catalog.ts\n")
	fmt.Fprintf(&out, "//\tgo run ./hack/gen-catalog\n\n")
	fmt.Fprintf(&out, "package %s\n\n", engine)
	fmt.Fprintf(&out, "import \"github.com/flanksource/recon/internal/engines\"\n\n")
	fmt.Fprintf(&out, "// catalog is %s's option catalog: what a profile for this engine may set.\n", engine)
	fmt.Fprintf(&out, "var catalog = engines.Sections{\n")

	for _, s := range sections {
		fmt.Fprintf(&out, "\t{\n")
		fmt.Fprintf(&out, "\t\tID: %s,\n", quote(s.ID))
		fmt.Fprintf(&out, "\t\tTitle: %s,\n", quote(s.Title))
		if s.Description != "" {
			fmt.Fprintf(&out, "\t\tDescription: %s,\n", quote(s.Description))
		}
		if s.SourceURL != "" {
			fmt.Fprintf(&out, "\t\tSourceURL: %s,\n", quote(s.SourceURL))
		}

		keys, properties, err := orderedProperties(s.Properties)
		if err != nil {
			return nil, fmt.Errorf("section %s: %w", s.ID, err)
		}

		fmt.Fprintf(&out, "\t\tProperties: []engines.Field{\n")
		for _, key := range keys {
			fmt.Fprintf(&out, "\t\t\t{Key: %s, Property: ", quote(key))
			writeProperty(&out, properties[key])
			fmt.Fprintf(&out, "},\n")
		}
		fmt.Fprintf(&out, "\t\t},\n\t},\n")
	}
	fmt.Fprintf(&out, "}\n")

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt: %w", err)
	}
	return formatted, nil
}

// orderedProperties recovers the declaration order of a JSON object, which
// decoding into a map would discard.
func orderedProperties(raw json.RawMessage) ([]string, map[string]property, error) {
	decoder := json.NewDecoder(bytes.NewReader(raw))
	// A schema keyword this generator does not model would otherwise vanish
	// silently and only surface as a fixture diff. Fail here instead.
	decoder.DisallowUnknownFields()
	if token, err := decoder.Token(); err != nil || token != json.Delim('{') {
		return nil, nil, fmt.Errorf("properties is not an object")
	}

	var keys []string
	properties := map[string]property{}
	for decoder.More() {
		token, err := decoder.Token()
		if err != nil {
			return nil, nil, err
		}
		key, ok := token.(string)
		if !ok {
			return nil, nil, fmt.Errorf("unexpected key %v", token)
		}
		var value property
		if err := decoder.Decode(&value); err != nil {
			return nil, nil, fmt.Errorf("option %s: %w", key, err)
		}
		keys = append(keys, key)
		properties[key] = value
	}
	return keys, properties, nil
}

func writeProperty(out *bytes.Buffer, p property) {
	fmt.Fprintf(out, "engines.Property{")
	var parts []string
	if p.Type != "" {
		parts = append(parts, fmt.Sprintf("Type: %s", quote(p.Type)))
	}
	if p.Title != "" {
		parts = append(parts, fmt.Sprintf("Title: %s", quote(p.Title)))
	}
	if p.Description != "" {
		parts = append(parts, fmt.Sprintf("Description: %s", quote(p.Description)))
	}
	if len(p.Enum) > 0 {
		quoted := make([]string, 0, len(p.Enum))
		for _, value := range p.Enum {
			quoted = append(quoted, quote(value))
		}
		parts = append(parts, fmt.Sprintf("Enum: []string{%s}", strings.Join(quoted, ", ")))
	}
	if p.MultipleOf != nil {
		parts = append(parts, fmt.Sprintf("MultipleOf: engines.Num(%s)", number(*p.MultipleOf)))
	}
	if p.Minimum != nil {
		parts = append(parts, fmt.Sprintf("Minimum: engines.Num(%s)", number(*p.Minimum)))
	}
	if p.Maximum != nil {
		parts = append(parts, fmt.Sprintf("Maximum: engines.Num(%s)", number(*p.Maximum)))
	}
	if p.ArrayDisplay != "" {
		parts = append(parts, fmt.Sprintf("ArrayDisplay: %s", quote(p.ArrayDisplay)))
	}
	if p.Items != nil {
		var items bytes.Buffer
		writeProperty(&items, *p.Items)
		parts = append(parts, fmt.Sprintf("Items: &%s", items.String()))
	}
	fmt.Fprintf(out, "%s}", strings.Join(parts, ", "))
}

func number(value float64) string {
	if value == float64(int64(value)) {
		return strconv.FormatInt(int64(value), 10)
	}
	return strconv.FormatFloat(value, 'g', -1, 64)
}

func quote(value string) string { return strconv.Quote(value) }

func moduleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found above %s", dir)
		}
		dir = parent
	}
}

func mustRel(root, path string) string {
	rel, err := filepath.Rel(root, path)
	if err != nil {
		return path
	}
	return rel
}
