package main

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

const commentWidth = 80

// render emits every generated file, keyed by name.
//
// One file per OCSF type, carrying its struct and the enumerations it owns,
// rather than one file holding every type: a single file would run past a
// thousand lines, and looking up Evidences should mean opening
// evidences.generated.go. Sorted throughout, so re-running against an unchanged
// schema produces byte-identical output and -check means what it says.
func render(built model) (map[string][]byte, error) {
	byOwner := map[string][]renderedEnum{}
	for _, enum := range built.Enums {
		byOwner[enum.Owner] = append(byOwner[enum.Owner], enum)
	}

	sources := map[string]string{"schema.generated.go": renderSchema(built)}
	for _, definition := range append([]renderedType{built.Root}, built.Objects...) {
		name := strings.ReplaceAll(definition.OCSF, "/", "_") + ".generated.go"
		sources[name] = renderType(built, definition, byOwner[definition.OCSF])
	}

	out := make(map[string][]byte, len(sources))
	for name, source := range sources {
		formatted, err := format.Source([]byte(source))
		if err != nil {
			return nil, fmt.Errorf("format %s: %w", name, err)
		}
		out[name] = formatted
	}
	return out, nil
}

func header(built model, summary string) string {
	var out strings.Builder
	out.WriteString("// Code generated by hack/gen-ocsf. DO NOT EDIT.\n//\n")
	for _, line := range wrapComment("", summary, commentWidth) {
		out.WriteString(line + "\n")
	}
	out.WriteString("//\n")
	fmt.Fprintf(&out, "// Source: OCSF %s, class %s (%d).\n",
		built.Version, built.ClassOCSF, built.ClassUID)
	out.WriteString("//\n// Regenerate with:\n//\tgo run ./hack/gen-ocsf\n\n")
	out.WriteString("package ocsf\n\n")
	return out.String()
}

func renderType(built model, definition renderedType, enums []renderedEnum) string {
	summary := fmt.Sprintf("The OCSF %s object.", definition.Caption)
	if definition.OCSF == built.ClassOCSF {
		summary = fmt.Sprintf("The OCSF %s class, pruned to the attributes recon populates.",
			definition.Caption)
	}

	var out strings.Builder
	out.WriteString(header(built, summary))
	writeImports(&out, definition, enums)
	writeStruct(&out, definition, built)
	for _, enum := range enums {
		writeEnum(&out, enum)
	}
	return out.String()
}

func writeImports(out *strings.Builder, definition renderedType, enums []renderedEnum) {
	var imports []string
	for _, member := range definition.Fields {
		if strings.Contains(member.GoType, "json.RawMessage") {
			imports = append(imports, `"encoding/json"`)
			break
		}
	}
	if len(enums) > 0 {
		imports = append(imports, `"strconv"`)
	}
	switch len(imports) {
	case 0:
	case 1:
		fmt.Fprintf(out, "import %s\n\n", imports[0])
	default:
		sort.Strings(imports)
		fmt.Fprintf(out, "import (\n\t%s\n)\n\n", strings.Join(imports, "\n\t"))
	}
}

func writeStruct(out *strings.Builder, definition renderedType, built model) {
	doc := fmt.Sprintf("%s is the OCSF %s object. %s",
		definition.Name, definition.Caption, definition.Description)
	if definition.OCSF == built.ClassOCSF {
		doc = fmt.Sprintf("%s is OCSF class %d in category %d. %s",
			definition.Name, built.ClassUID, built.CategoryUID, definition.Description)
	}
	for _, line := range wrapComment("", doc, commentWidth) {
		out.WriteString(line + "\n")
	}
	if len(definition.AtLeastOne) > 0 {
		out.WriteString("//\n")
		for _, line := range wrapComment("", fmt.Sprintf(
			"OCSF requires at least one of: %s. Validate enforces it, because no struct "+
				"shape can.", strings.Join(definition.AtLeastOne, ", ")), commentWidth) {
			out.WriteString(line + "\n")
		}
	}

	fmt.Fprintf(out, "type %s struct {\n", definition.Name)
	for i, member := range definition.Fields {
		if i > 0 {
			out.WriteString("\n")
		}
		writeField(out, member)
	}
	out.WriteString("}\n\n")
}

func writeField(out *strings.Builder, member field) {
	doc := member.Caption
	if member.Description != "" {
		doc = member.Caption + ". " + member.Description
	}
	for _, line := range wrapComment("\t", doc, commentWidth) {
		out.WriteString(line + "\n")
	}
	note := member.Requirement
	if member.Profile != "" {
		note += ", under profile " + member.Profile
	}
	fmt.Fprintf(out, "\t// OCSF: %s (%s)\n", member.OCSF, note)

	tag := member.OCSF
	if member.OmitEmpty {
		tag += ",omitempty"
	}
	fmt.Fprintf(out, "\t%s %s `json:%s`\n", member.Name, member.GoType, strconv.Quote(tag))
}

func writeEnum(out *strings.Builder, enum renderedEnum) {
	doc := fmt.Sprintf("%s is OCSF %s.%s. %s", enum.Name, enum.Owner, enum.OCSF, enum.Description)
	for _, line := range wrapComment("", doc, commentWidth) {
		out.WriteString(line + "\n")
	}
	fmt.Fprintf(out, "type %s int\n\n", enum.Name)

	out.WriteString("const (\n")
	for i, member := range enum.Members {
		if i > 0 {
			out.WriteString("\n")
		}
		for _, line := range wrapComment("\t", member.Description, commentWidth) {
			out.WriteString(line + "\n")
		}
		fmt.Fprintf(out, "\t%s %s = %d\n", member.Name, enum.Name, member.Value)
	}
	out.WriteString(")\n\n")

	fmt.Fprintf(out, "// String returns the caption OCSF publishes for the value, so a rendered\n"+
		"// %s reads the way the schema browser shows it.\n", enum.Name)
	fmt.Fprintf(out, "func (v %s) String() string {\n\tswitch v {\n", enum.Name)
	for _, member := range enum.Members {
		fmt.Fprintf(out, "\tcase %s:\n\t\treturn %s\n", member.Name, strconv.Quote(member.Caption))
	}
	fmt.Fprintf(out, "\t}\n\treturn %s + strconv.Itoa(int(v)) + \")\"\n}\n\n",
		strconv.Quote(enum.Name+"("))
}

func renderSchema(built model) string {
	var out strings.Builder
	out.WriteString(header(built,
		"The class identity, requirement levels and object constraints Validate reads."))

	fmt.Fprintf(&out, "// Version is the OCSF release these types were generated from.\n"+
		"const Version = %s\n\n", strconv.Quote(built.Version))

	out.WriteString("const (\n")
	for _, line := range wrapComment("\t", fmt.Sprintf(
		"ClassUID identifies %s. OCSF composes it as category_uid*1000 plus the class's own uid.",
		built.Caption), commentWidth) {
		out.WriteString(line + "\n")
	}
	fmt.Fprintf(&out, "\tClassUID = %d\n\n", built.ClassUID)
	for _, line := range wrapComment("\t", "CategoryUID identifies the Findings category.", commentWidth) {
		out.WriteString(line + "\n")
	}
	fmt.Fprintf(&out, "\tCategoryUID = %d\n", built.CategoryUID)
	out.WriteString(")\n\n")

	out.WriteString("// TypeUID composes the OCSF type identifier, which narrows a class to one\n" +
		"// activity. OCSF defines it as class_uid*100 plus the activity id.\n")
	out.WriteString("func TypeUID(activity ActivityID) int64 {\n" +
		"\treturn int64(ClassUID)*100 + int64(activity)\n}\n\n")

	writeProfiles(&out, built)
	writeRequirements(&out, built)
	writeConstraints(&out, built)
	writeObjectNames(&out, built)
	return out.String()
}

func writeObjectNames(out *strings.Builder, built model) {
	out.WriteString(`
// ObjectNames maps each generated Go type to the OCSF object it represents, so
// Validate can find an object's constraints while walking a record. Generated
// rather than derived by lowercasing, because the two names diverge wherever an
// initialism or an extension prefix is involved.
var ObjectNames = map[string]string{
`)
	named := append([]renderedType{built.Root}, built.Objects...)
	sort.Slice(named, func(i, j int) bool { return named[i].Name < named[j].Name })
	for _, definition := range named {
		fmt.Fprintf(out, "\t%s: %s,\n", strconv.Quote(definition.Name), strconv.Quote(definition.OCSF))
	}
	out.WriteString("}\n")
}

func writeProfiles(out *strings.Builder, built model) {
	for _, line := range wrapComment("", fmt.Sprintf(
		"Profiles are the OCSF profiles %s may declare. A profile is what raises an "+
			"attribute's requirement level, so which ones a record declares in "+
			"metadata.profiles decides what Validate demands of it.", built.Caption), commentWidth) {
		out.WriteString(line + "\n")
	}
	out.WriteString("var Profiles = []string{\n")
	for _, profile := range built.Profiles {
		fmt.Fprintf(out, "\t%s,\n", strconv.Quote(profile))
	}
	out.WriteString("}\n\n")
}

func writeRequirements(out *strings.Builder, built model) {
	out.WriteString(`// Requirement is what OCSF asks of one attribute.
//
// Profile is empty when the requirement is unconditional, and names a profile
// when it applies only to a record that declares it: cloud is optional on a
// bare detection finding and required on one that audits a cloud account.
type Requirement struct {
	Attribute string
	Level     string
	Profile   string
}

// Requirements is the requirement level of every attribute these types carry.
var Requirements = []Requirement{
`)
	members := append([]field(nil), built.Root.Fields...)
	sort.Slice(members, func(i, j int) bool { return members[i].OCSF < members[j].OCSF })
	for _, member := range members {
		fmt.Fprintf(out, "\t{Attribute: %s, Level: %s, Profile: %s},\n",
			strconv.Quote(member.OCSF), strconv.Quote(member.Requirement), strconv.Quote(member.Profile))
	}
	out.WriteString("}\n\n")
}

func writeConstraints(out *strings.Builder, built model) {
	out.WriteString(`// Constraint is a condition OCSF states about an object that a struct shape
// cannot express, so Validate checks it instead.
type Constraint struct {
	AtLeastOne []string
	JustOne    []string
}

// Constraints holds those conditions, keyed by OCSF object name. Only
// attributes these generated types actually carry appear: a constraint naming a
// pruned attribute would reject records that are in fact valid.
var Constraints = map[string]Constraint{
`)
	for _, definition := range built.Objects {
		if len(definition.AtLeastOne) == 0 && len(definition.JustOne) == 0 {
			continue
		}
		fmt.Fprintf(out, "\t%s: {", strconv.Quote(definition.OCSF))
		if len(definition.AtLeastOne) > 0 {
			fmt.Fprintf(out, "AtLeastOne: []string{%s}", quoteList(definition.AtLeastOne))
		}
		if len(definition.JustOne) > 0 {
			if len(definition.AtLeastOne) > 0 {
				out.WriteString(", ")
			}
			fmt.Fprintf(out, "JustOne: []string{%s}", quoteList(definition.JustOne))
		}
		out.WriteString("},\n")
	}
	out.WriteString("}\n")
}

func quoteList(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, strconv.Quote(value))
	}
	return strings.Join(quoted, ", ")
}
